[build]
  [[build.env]]
    name = "BP_GO_BUILD_FLAGS"
    value = "-ldflags=-s -w"

  # Paketo Buildpacks: single target for server binary
  [[build.env]]
    name = "BP_GO_TARGETS"
    value = "./cmd/server"

[metadata]
  include-files = ["server"]
