// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chapter struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Order       int          `json:"order"`
	ContentHTML string       `json:"contentHtml"`
	Paragraphs  []*Paragraph `json:"paragraphs"`
	Media       []*Media     `json:"media"`
}

type CreateChapterInput struct {
	EpubID      string  `json:"epubId"`
	Title       string  `json:"title"`
	Order       int     `json:"order"`
	ContentHTML *string `json:"contentHtml,omitempty"`
}

type CreateEpubInput struct {
	Title    string `json:"title"`
	Language string `json:"language"`
}

type CreateMediaInput struct {
	ChapterID string `json:"chapterId"`
	Type      string `json:"type"`
	URL       string `json:"url"`
	MimeType  string `json:"mimeType"`
	FileSize  int    `json:"fileSize"`
}

type Epub struct {
	ID        string          `json:"id"`
	Title     string          `json:"title"`
	Language  string          `json:"language"`
	CreatedAt string          `json:"createdAt"`
	UpdatedAt string          `json:"updatedAt"`
	Chapters  []*Chapter      `json:"chapters"`
	Metadata  []*MetadataItem `json:"metadata"`
}

type GenerateTextInput struct {
	Prompt      string   `json:"prompt"`
	MaxLength   *int     `json:"maxLength,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
}

// @context https://gftd.ai/ontology/epub-editor#
// @type cpm:Activity
// @id https://gftd.ai/activity/generate-text
//
// AI Generator GraphQL schema definitions
type GeneratedText struct {
	Text       string   `json:"text"`
	Confidence *float64 `json:"confidence,omitempty"`
}

type Media struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	URL      string `json:"url"`
	MimeType string `json:"mimeType"`
	FileSize int    `json:"fileSize"`
}

// @context https://gftd.ai/ontology/epub-editor#
// @type cpm:Resource
// @id https://gftd.ai/resource/epub-document
//
// EPUB Document GraphQL schema definitions
type MetadataItem struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Paragraph struct {
	ID          string `json:"id"`
	Order       int    `json:"order"`
	ContentHTML string `json:"contentHtml"`
}

type ProofreadInput struct {
	ChapterID string  `json:"chapterId"`
	Language  *string `json:"language,omitempty"`
}

// @context https://gftd.ai/ontology/epub-editor#
// @type cpm:Service
// @id https://gftd.ai/performer/service/graphql-go
//
// GraphQL API service for EPUB Editor Tool (Go implementation)
// Provides Query, Mutation, and Subscription operations for EPUB editing
type Query struct {
}

type Subscription struct {
}

type SummarizeInput struct {
	ChapterID string `json:"chapterId"`
	MaxLength *int   `json:"maxLength,omitempty"`
}

type TranslateInput struct {
	ChapterID      string  `json:"chapterId"`
	TargetLanguage string  `json:"targetLanguage"`
	SourceLanguage *string `json:"sourceLanguage,omitempty"`
}

type UpdateChapterInput struct {
	ID          string  `json:"id"`
	Title       *string `json:"title,omitempty"`
	Order       *int    `json:"order,omitempty"`
	ContentHTML *string `json:"contentHtml,omitempty"`
}

type UpdateEpubInput struct {
	ID       string  `json:"id"`
	Title    *string `json:"title,omitempty"`
	Language *string `json:"language,omitempty"`
}

type UpdateMetadataInput struct {
	EpubID string `json:"epubId"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}
