#!/usr/bin/env nbb
;; 260123-jump/scripts/gen-catalog.cljs — production-catalog/*.edn を episode.edn から生成する。
;;
;; catalog の各ファイルは冒頭で自分をこう名乗っている:
;;
;;   ;; Generated by reading <episode.edn> — every number here is counted from the
;;   ;; episode, none asserted. Regenerate rather than hand-edit.
;;
;; **だが生成器が repo に無かった**（2026-08-13 実測）。名乗りだけがあって、
;; 再生成する手段が無い状態は、索引 _index.edn と同じ形の欠陥である —— 手で
;; 直せば「数えた」と書いてある嘘の数が入る。ここでその生成器を置く。
;;
;; scripts/produce.cljs は plan/pages・plan/panels を実エピソードと突き合わせて
;; 食い違えば warning を出す。**この生成器はその warning が構造的に出ないようにする**
;; ——数えた値しか書かないので。
;;
;; usage:
;;   nbb scripts/gen-catalog.cljs            # 生成して書く
;;   nbb scripts/gen-catalog.cljs --check    # 最新か検査（書かない）
;;
;; 終了コード: 0 一致 / 1 STALE / 2 答えられなかった（入力が読めない・少なすぎる）

(ns gen-catalog
  (:require ["fs" :as fs]
            ["path" :as path]
            [clojure.edn :as edn]
            [clojure.string :as str]
            [cljs.pprint]))

(def ^:private episodes-dir "260123-jump/resources/episodes")
(def ^:private catalog-dir "production-catalog")
(def ^:private min-episodes 3)

(defn- read-edn [f]
  (try (edn/read-string (fs/readFileSync f "utf8"))
       (catch :default e {::error (str e)})))

(defn- nested [m k]
  (let [v (get m k)] (if (string? v) (edn/read-string v) v)))

(defn- count-panels [pages]
  (reduce + 0 (map #(count (or (:gh/panels %) (:panels %))) pages)))

(def ^:private resources-root "260123-jump/resources")

(defn- panel-image-url
  "そのコマが「現在採用している」画像の URL。arc0-1 系は
  :gh/generatedImages（候補の配列）+ :gh/currentImageIndex を持ち、
  各要素は #:gh{:imageUrl … :model … :generatedAt …}。
  古い :generatedImageUrl / :gh/generatedImageUrl も見るが、**実測 2026-08-14 では
  arc0-1 の 255 件すべてが、実在しないファイル名（_v2）を指していた**。"
  [p]
  (or (when-let [v (:gh/generatedImages p)]
        (:gh/imageUrl (get v (or (:gh/currentImageIndex p) 0))))
      (:gh/generatedImageUrl p)
      (:generatedImageUrl p)))

(defn- image-bytes-present?
  "**URL があることと、バイトが取れることは別である。**
  この repo の画像は git-annex の symlink なので、tree にパスが在っても
  実体は B2（remote `b2`, bucket com-junkawasaki-annex, encryption=hybrid）に在り、
  `git annex get` するまで**リンクは切れている**。
  fs/existsSync は symlink を辿るので、実体が無ければ false になる——それが欲しい。"
  [url]
  (and (string? url)
       (fs/existsSync (path/join resources-root url))))

(defn- image-status
  "コマの画像の状態を 3 つに分ける。**2 つではない。**
    :present   URL があり、バイトも取れる
    :annexed   URL はあるが、バイトが無い（annex 未取得 or 参照切れ）
    :none      URL that が無い（まだ生成していない）
  **:annexed を :present と同じ数に混ぜたのが、2026-08-14 まであった欠陥。**
  production-catalog は『255 コマ生成済み』と書いていたが、**実在は 0** だった。"
  [p]
  (let [u (panel-image-url p)]
    (cond (nil? u) :none
          (image-bytes-present? u) :present
          :else :annexed)))

(defn- image-counts [pages]
  (frequencies (map image-status (mapcat #(or (:gh/panels %) (:panels %)) pages))))

(defn- plan-for [slug ep-path ep idx]
  (let [pages (nested ep :gh/pages)]
    {:plan/id slug
     :plan/source ep-path
     :plan/episode-id (:gh/episodeId ep)
     :plan/episode-index (or (:gh/episodeIndex ep) idx)
     :plan/arc (:gh/arc ep)
     :plan/tagline (:gh/presentationTagline ep)
     :plan/pages (count pages)
     :plan/panels (count-panels pages)
     ;; **3 つに分けて書く。**`:plan/panels-already-generated` は「URL がある」の意味に
     ;; 読まれてきたので、名前を変えずに**値の意味を狭めた**——ここは
     ;; **バイトが取れたコマ数**だけを入れる。取れなかった分は :plan/panels-annexed に出す。
     :plan/panels-already-generated (get (image-counts pages) :present 0)
     :plan/panels-annexed (get (image-counts pages) :annexed 0)
     :plan/image-note (str "panels-already-generated は**バイトが取れたコマ数**。"
                           "panels-annexed は URL はあるがローカルに実体が無いコマ"
                           "（git-annex 未取得／参照切れ）。"
                           "`git annex get` していない作業ツリーでは前者が 0 になるのが正常。")
     :plan/version 1}))

(defn- render [plan]
  (str ";; Generated by reading " (:plan/source plan)
       " — every number here is counted from the\n"
       ";; episode, none asserted. Regenerate with `nbb scripts/gen-catalog.cljs`; do not hand-edit.\n"
       (with-out-str (cljs.pprint/pprint plan))))

(defn -main [& args]
  (let [check? (some #{"--check"} (vec args))]
    (when-not (fs/existsSync episodes-dir)
      (println "gen-catalog: episodes dir not found. Run from the repo root.\n  Refusing to report a result.")
      (js/process.exit 2))
    (let [slugs (->> (fs/readdirSync episodes-dir)
                     (remove #{"_archive"})
                     (filter #(fs/existsSync (path/join episodes-dir % "episode.edn")))
                     sort vec)
          _ (when (< (count slugs) min-episodes)
              (println (str "gen-catalog: found only " (count slugs) " episode.edn (min " min-episodes ").\n"
                            "  Refusing to write a catalog from a tree this small."))
              (js/process.exit 2))
          reads (for [[i s] (map-indexed vector slugs)]
                  (let [f (path/join episodes-dir s "episode.edn")
                        ep (read-edn f)]
                    (if (::error ep)
                      {:slug s :ok false :err (::error ep)}
                      {:slug s :ok true :plan (plan-for s f (first ep) (inc i))})))
          bad (remove :ok reads)]
      (doseq [{:keys [slug err]} bad] (println "  UNREADABLE" slug "—" err))
      (when (seq bad)
        (println "gen-catalog:" (count bad) "unreadable episode(s). Refusing to report a pass.")
        (js/process.exit 2))

      ;; **孤児の検出。**episode が消えた（改名された）のに catalog が残ると、
      ;; produce.cljs が存在しない episode を指す plan を読める状態になる。
      ;; 実測 2026-08-14: arc12-keiei → keiei の改名で実際に孤児が 1 件出た。
      (let [want (set (map #(str % ".edn") slugs))
            have (if (fs/existsSync catalog-dir)
                   (set (filter #(str/ends-with? % ".edn") (fs/readdirSync catalog-dir)))
                   #{})
            orphans (sort (remove want have))]
        (doseq [o orphans] (println "  ORPHAN" o "— この plan が指す episode.edn は存在しない"))
        (when (seq orphans)
          (if check?
            (do (println "gen-catalog:" (count orphans) "orphan(s). STALE")
                (js/process.exit 1))
            (do (doseq [o orphans] (fs/unlinkSync (path/join catalog-dir o)))
                (println "gen-catalog: removed" (count orphans) "orphan(s)")))))

      (println (str "gen-catalog: EPISODES\t" (count slugs)))
      (let [results
            (doall
             (for [{:keys [slug plan]} reads]
               (let [out (path/join catalog-dir (str slug ".edn"))
                     text (render plan)
                     cur (when (fs/existsSync out) (fs/readFileSync out "utf8"))
                     state (cond (nil? cur) :new (= cur text) :fresh :else :stale)]
                 (println (str "  " (name state) "\t" slug
                               "\t" (:plan/pages plan) "頁 / " (:plan/panels plan) "コマ"
                               " / 実体あり " (:plan/panels-already-generated plan)
                               " / annex待ち " (:plan/panels-annexed plan)))
                 (when-not check? (fs/writeFileSync out text))
                 state)))]
        (if check?
          (if (every? #{:fresh} results)
            (println "gen-catalog: FRESH")
            (do (println "gen-catalog: STALE — regenerate with `nbb scripts/gen-catalog.cljs`")
                (js/process.exit 1)))
          (println "gen-catalog: wrote" (count results) "catalog entr(ies)"))))))

(apply -main *command-line-args*)
