FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

# プロジェクト全体をコピー
COPY . .

# content-creatorディレクトリに移動して依存関係をインストール
WORKDIR /app/performers/actors/content-creator

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "dev"]

