/**
 * @context https://gftd.ai/ontology/epub-editor#
 * @type cpm:Activity
 * @id https://gftd.ai/activity/manage-chapters
 * 
 * GraphQL mutations for EPUB operations
 * Re-exports generated DocumentNodes from graphql.ts
 * 
 * Note: These are generated by GraphQL Codegen from mutations.graphql
 * Run `pnpm codegen` after updating mutations.graphql to regenerate types
 */
export {
  CreateEpubDocument as CREATE_EPUB,
  UpdateEpubDocument as UPDATE_EPUB,
  DeleteEpubDocument as DELETE_EPUB,
  CreateChapterDocument as CREATE_CHAPTER,
  UpdateChapterDocument as UPDATE_CHAPTER,
  DeleteChapterDocument as DELETE_CHAPTER,
  CreateMediaDocument as CREATE_MEDIA,
  UpdateMetadataDocument as UPDATE_METADATA,
  GenerateTextDocument as GENERATE_TEXT,
  SummarizeChapterDocument as SUMMARIZE_CHAPTER,
  ProofreadChapterDocument as PROOFREAD_CHAPTER,
  TranslateChapterDocument as TRANSLATE_CHAPTER,
  // AnalyzeEmotionsDocument will be available after running `pnpm codegen`
  // Uncomment after GraphQL server is running and codegen has been executed
  // AnalyzeEmotionsDocument as ANALYZE_EMOTIONS,
} from '@/generated/graphql';

// Temporary: Use gql tag until documents are generated
// Remove this after running `pnpm codegen`
import gql from 'graphql-tag';
export const ANALYZE_EMOTIONS = gql`
  mutation AnalyzeEmotions($input: AnalyzeEmotionsInput!) {
    analyzeEmotions(input: $input) {
      emotionVector {
        emotion
        score
      }
      createdAt
      language
    }
  }
`;

export const CREATE_GRAPH_LINK = gql`
  mutation CreateGraphLink($input: CreateGraphLinkInput!) {
    createGraphLink(input: $input) {
      id
      sourceNodeType
      sourceNodeId
      targetNodeType
      targetNodeId
      linkType
      properties
      createdAt
      updatedAt
    }
  }
`;

export const UPDATE_GRAPH_LINK = gql`
  mutation UpdateGraphLink($input: UpdateGraphLinkInput!) {
    updateGraphLink(input: $input) {
      id
      sourceNodeType
      sourceNodeId
      targetNodeType
      targetNodeId
      linkType
      properties
      createdAt
      updatedAt
    }
  }
`;

export const DELETE_GRAPH_LINK = gql`
  mutation DeleteGraphLink($id: ID!) {
    deleteGraphLink(id: $id)
  }
`;

export const CREATE_GRAPH_INCIDENCE = gql`
  mutation CreateGraphIncidence($input: CreateGraphIncidenceInput!) {
    createGraphIncidence(input: $input) {
      id
      nodeType
      nodeId
      linkId
      role
      properties
      createdAt
      updatedAt
    }
  }
`;

export const UPDATE_GRAPH_INCIDENCE = gql`
  mutation UpdateGraphIncidence($input: UpdateGraphIncidenceInput!) {
    updateGraphIncidence(input: $input) {
      id
      nodeType
      nodeId
      linkId
      role
      properties
      createdAt
      updatedAt
    }
  }
`;

export const DELETE_GRAPH_INCIDENCE = gql`
  mutation DeleteGraphIncidence($id: ID!) {
    deleteGraphIncidence(id: $id)
  }
`;

