/**
 * @context https://gftd.ai/ontology/epub-editor#
 * @type cpm:Activity
 * @id https://gftd.ai/activity/manage-chapters
 * 
 * GraphQL mutations for EPUB operations
 * Re-exports generated DocumentNodes from graphql.ts
 * 
 * Note: These are generated by GraphQL Codegen from mutations.graphql
 * Run `pnpm codegen` after updating mutations.graphql to regenerate types
 */
export {
  CreateEpubDocument as CREATE_EPUB,
  UpdateEpubDocument as UPDATE_EPUB,
  DeleteEpubDocument as DELETE_EPUB,
  CreateChapterDocument as CREATE_CHAPTER,
  UpdateChapterDocument as UPDATE_CHAPTER,
  DeleteChapterDocument as DELETE_CHAPTER,
  CreateMediaDocument as CREATE_MEDIA,
  UpdateMetadataDocument as UPDATE_METADATA,
  GenerateTextDocument as GENERATE_TEXT,
  SummarizeChapterDocument as SUMMARIZE_CHAPTER,
  ProofreadChapterDocument as PROOFREAD_CHAPTER,
  TranslateChapterDocument as TRANSLATE_CHAPTER,
  AnalyzeEmotionsDocument as ANALYZE_EMOTIONS,
  CreateGraphLinkDocument as CREATE_GRAPH_LINK,
  UpdateGraphLinkDocument as UPDATE_GRAPH_LINK,
  DeleteGraphLinkDocument as DELETE_GRAPH_LINK,
  CreateGraphIncidenceDocument as CREATE_GRAPH_INCIDENCE,
  UpdateGraphIncidenceDocument as UPDATE_GRAPH_INCIDENCE,
  DeleteGraphIncidenceDocument as DELETE_GRAPH_INCIDENCE,
  GenerateContentWithMultiAgentDocument as GENERATE_CONTENT_WITH_MULTI_AGENT,
  ClassifyNodeDocument as CLASSIFY_NODE,
  ReclassifySelectedNodesDocument as RECLASSIFY_SELECTED_NODES,
} from '@/generated/graphql';

// Conditionally export UpdateNodeTypeDocument if it exists
// This will be available after running codegen with updated schema
// Note: This export may be undefined until GraphQL server is restarted and codegen is run
import * as GeneratedGraphQL from '@/generated/graphql';
export const UPDATE_NODE_TYPE = (GeneratedGraphQL as any).UpdateNodeTypeDocument as typeof GeneratedGraphQL.UpdateNodeTypeDocument | undefined;


