//! Postgres capability helper functions
//! 
//! Helper functions for using the Postgres capability
//! 
//! NOTE: These functions use wit_bindgen generated bindings
//! The bindings are generated by wash build automatically based on the WIT world definition
//! 
//! The generated bindings will be available as:
//! - wasmcloud::postgres::query::query()
//! - wasmcloud::postgres::types::PgValue
//! - wasmcloud::postgres::types::ResultRow
//! - wasmcloud::postgres::types::QueryError

use serde_json::Value;

// Import generated bindings from wit_bindgen
// These will be available once wash build generates the bindings
// For now, we'll use a conditional compilation approach
#[cfg(feature = "postgres-bindings")]
use wasmcloud::postgres::query::query;
#[cfg(feature = "postgres-bindings")]
use wasmcloud::postgres::types::{PgValue, ResultRow, QueryError};

// Placeholder types for when bindings are not yet available
// These match the WIT types defined in wit/deps/postgres/wit/types.wit
// Placeholder types matching WIT types
// These will be replaced with actual generated types once wit_bindgen bindings are available
#[derive(Debug, Clone)]
pub enum PgValue {
    Text(String),
    Int32(i32),
    Int64(i64),
    Float32((u64, i16, i8)), // hashable-f64: (mantissa, exp, sign)
    Float64((u64, i16, i8)), // hashable-f64: (mantissa, exp, sign)
    Bool(bool),
    Null,
}

#[derive(Debug)]
pub struct ResultRowEntry {
    pub column_name: String,
    pub value: PgValue,
}

pub type ResultRow = Vec<ResultRowEntry>;

#[derive(Debug)]
pub enum QueryError {
    InvalidParams(String),
    InvalidQuery(String),
    Unexpected(String),
}

// Placeholder function matching WIT interface signature
// This will be replaced with actual generated function once wit_bindgen bindings are available
fn query(_sql: &str, _params: &[PgValue]) -> Result<Vec<ResultRow>, QueryError> {
    Err(QueryError::Unexpected(
        "Postgres capability not yet available - wit_bindgen bindings needed".to_string(),
    ))
}

/// Query all entities from ir_entities table
pub fn query_entities() -> Result<Vec<Value>, String> {
    // NOTE: This function will use wit_bindgen generated bindings once available
    // For now, it uses placeholder implementation
    // The actual implementation will use wasmcloud::postgres::query::query()
    // and wasmcloud::postgres::types::{PgValue, ResultRow, QueryError}
    
    match query(
        "SELECT entity_id, entity_type, name, jsonld_data, llm_label, embed_hint, image_prompt, video_prompt, embedding_id, created_at, updated_at FROM ir_entities ORDER BY created_at DESC",
        &[],
    ) {
        Ok(rows) => {
            let mut entities = Vec::new();
            for row in rows {
                let mut entity = serde_json::Map::new();
                // ResultRow is a list of result-row-entry (column-name, value)
                for entry in row {
                    let value = match &entry.value {
                        PgValue::Text(s) => {
                            if entry.column_name == "jsonld_data" {
                                // Parse JSON-LD data
                                serde_json::from_str(s).unwrap_or(Value::String(s.clone()))
                            } else {
                                Value::String(s.clone())
                            }
                        },
                        PgValue::Int32(n) => Value::Number((*n).into()),
                        PgValue::Int64(n) => Value::Number((*n).into()),
                        PgValue::Float32(f) => {
                            // Convert hashable-f64 to f64
                            let (mantissa, exp, sign) = *f;
                            let f64_val = if sign == 1 {
                                -(mantissa as f64) * 2.0_f64.powi(exp as i32)
                            } else {
                                (mantissa as f64) * 2.0_f64.powi(exp as i32)
                            };
                            Value::Number(serde_json::Number::from_f64(f64_val).unwrap_or(0.into()))
                        },
                        PgValue::Float64(f) => {
                            // Convert hashable-f64 to f64
                            let (mantissa, exp, sign) = *f;
                            let f64_val = if sign == 1 {
                                -(mantissa as f64) * 2.0_f64.powi(exp as i32)
                            } else {
                                (mantissa as f64) * 2.0_f64.powi(exp as i32)
                            };
                            Value::Number(serde_json::Number::from_f64(f64_val).unwrap_or(0.into()))
                        },
                        PgValue::Bool(b) => Value::Bool(*b),
                        PgValue::Null => Value::Null,
                        _ => Value::String(format!("{:?}", entry.value)),
                    };
                    entity.insert(entry.column_name.clone(), value);
                }
                entities.push(Value::Object(entity));
            }
            Ok(entities)
        },
        Err(e) => Err(format!("Query failed: {:?}", e)),
    }
}

/// Create a new entity in ir_entities table
pub fn create_entity(_entity_data: &Value) -> Result<String, String> {
    // TODO: Implement using wasmcloud::postgres::query once bindings are available
    Err("Postgres capability not yet available - wit_bindgen bindings needed".to_string())
    
    // Once bindings are available, implement the full logic:
    // Placeholder implementation - will be replaced with actual Postgres query
    // See commented code below for full implementation
}

/// Get entity by ID from ir_entities table
pub fn get_entity(_id: &str) -> Result<Value, String> {
    // TODO: Implement using wasmcloud::postgres::query once bindings are available
    Err("Postgres capability not yet available - wit_bindgen bindings needed".to_string())
}

/// Update entity in ir_entities table
pub fn update_entity(_id: &str, _entity_data: &Value) -> Result<(), String> {
    // TODO: Implement using wasmcloud::postgres::query once bindings are available
    Err("Postgres capability not yet available - wit_bindgen bindings needed".to_string())
}

/// Delete entity from ir_entities table
pub fn delete_entity(_id: &str) -> Result<(), String> {
    // TODO: Implement using wasmcloud::postgres::query once bindings are available
    Err("Postgres capability not yet available - wit_bindgen bindings needed".to_string())
}

