apiVersion: v1
kind: Secret
metadata:
  name: {{ include "producer-storyboard.fullname" . }}-secrets
  labels:
    {{- include "producer-storyboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.grpcGo.secrets.OPENAI_API_KEY }}
  openai-api-key: {{ .Values.grpcGo.secrets.OPENAI_API_KEY }}
  {{- end }}
  {{- if .Values.grpcGo.secrets.HUME_API_KEY }}
  hume-api-key: {{ .Values.grpcGo.secrets.HUME_API_KEY }}
  {{- end }}
  {{- if .Values.grpcGo.secrets.SUNO_API_KEY }}
  suno-api-key: {{ .Values.grpcGo.secrets.SUNO_API_KEY }}
  {{- end }}
  {{- if .Values.grpcGo.secrets.RUNWAY_API_KEY }}
  runway-api-key: {{ .Values.grpcGo.secrets.RUNWAY_API_KEY }}
  {{- end }}
  {{- if .Values.grpcGo.secrets.HIGGSFIELD_API_KEY }}
  higgsfield-api-key: {{ .Values.grpcGo.secrets.HIGGSFIELD_API_KEY }}
  {{- end }}
  {{- if .Values.temporalWorker.secrets.CLERK_SECRET_KEY }}
  clerk-secret-key: {{ .Values.temporalWorker.secrets.CLERK_SECRET_KEY }}
  {{- end }}
