// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectAsset = `-- name: CreateProjectAsset :one
INSERT INTO project_assets (project_id, org_id, asset_type, asset_data, asset_format, filename, description, tags, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, asset_type, asset_format, filename, description, tags, metadata, created_at, updated_at
`

type CreateProjectAssetParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	OrgID       pgtype.Text `json:"org_id"`
	AssetType   string      `json:"asset_type"`
	AssetData   []byte      `json:"asset_data"`
	AssetFormat pgtype.Text `json:"asset_format"`
	Filename    pgtype.Text `json:"filename"`
	Description pgtype.Text `json:"description"`
	Tags        []string    `json:"tags"`
	Metadata    []byte      `json:"metadata"`
}

type CreateProjectAssetRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AssetType   string             `json:"asset_type"`
	AssetFormat pgtype.Text        `json:"asset_format"`
	Filename    pgtype.Text        `json:"filename"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProjectAsset(ctx context.Context, arg CreateProjectAssetParams) (CreateProjectAssetRow, error) {
	row := q.db.QueryRow(ctx, createProjectAsset,
		arg.ProjectID,
		arg.OrgID,
		arg.AssetType,
		arg.AssetData,
		arg.AssetFormat,
		arg.Filename,
		arg.Description,
		arg.Tags,
		arg.Metadata,
	)
	var i CreateProjectAssetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AssetType,
		&i.AssetFormat,
		&i.Filename,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectAsset = `-- name: DeleteProjectAsset :exec
DELETE FROM project_assets WHERE id = $1 AND org_id = $2
`

type DeleteProjectAssetParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

func (q *Queries) DeleteProjectAsset(ctx context.Context, arg DeleteProjectAssetParams) error {
	_, err := q.db.Exec(ctx, deleteProjectAsset, arg.ID, arg.OrgID)
	return err
}

const getProjectAsset = `-- name: GetProjectAsset :one
SELECT id, project_id, asset_type, asset_format, filename, description, tags, metadata, created_at, updated_at
FROM project_assets
WHERE id = $1 AND org_id = $2
`

type GetProjectAssetParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

type GetProjectAssetRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AssetType   string             `json:"asset_type"`
	AssetFormat pgtype.Text        `json:"asset_format"`
	Filename    pgtype.Text        `json:"filename"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectAsset(ctx context.Context, arg GetProjectAssetParams) (GetProjectAssetRow, error) {
	row := q.db.QueryRow(ctx, getProjectAsset, arg.ID, arg.OrgID)
	var i GetProjectAssetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AssetType,
		&i.AssetFormat,
		&i.Filename,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectAssetData = `-- name: GetProjectAssetData :one
SELECT asset_data, asset_format FROM project_assets WHERE id = $1 AND org_id = $2
`

type GetProjectAssetDataParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

type GetProjectAssetDataRow struct {
	AssetData   []byte      `json:"asset_data"`
	AssetFormat pgtype.Text `json:"asset_format"`
}

func (q *Queries) GetProjectAssetData(ctx context.Context, arg GetProjectAssetDataParams) (GetProjectAssetDataRow, error) {
	row := q.db.QueryRow(ctx, getProjectAssetData, arg.ID, arg.OrgID)
	var i GetProjectAssetDataRow
	err := row.Scan(&i.AssetData, &i.AssetFormat)
	return i, err
}

const listProjectAssets = `-- name: ListProjectAssets :many
SELECT id, project_id, asset_type, asset_format, filename, description, tags, metadata, created_at, updated_at
FROM project_assets
WHERE project_id = $1 AND org_id = $2
  AND ($3::VARCHAR IS NULL OR asset_type = $3)
  AND ($4::TEXT[] IS NULL OR tags && $4)
ORDER BY created_at DESC
`

type ListProjectAssetsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	OrgID     pgtype.Text `json:"org_id"`
	Column3   string      `json:"column_3"`
	Column4   []string    `json:"column_4"`
}

type ListProjectAssetsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AssetType   string             `json:"asset_type"`
	AssetFormat pgtype.Text        `json:"asset_format"`
	Filename    pgtype.Text        `json:"filename"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProjectAssets(ctx context.Context, arg ListProjectAssetsParams) ([]ListProjectAssetsRow, error) {
	rows, err := q.db.Query(ctx, listProjectAssets,
		arg.ProjectID,
		arg.OrgID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectAssetsRow
	for rows.Next() {
		var i ListProjectAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AssetType,
			&i.AssetFormat,
			&i.Filename,
			&i.Description,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectAsset = `-- name: UpdateProjectAsset :one
UPDATE project_assets
SET filename = COALESCE($3, filename),
    description = COALESCE($4, description),
    tags = COALESCE($5, tags),
    metadata = COALESCE($6, metadata),
    updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, project_id, asset_type, asset_format, filename, description, tags, metadata, created_at, updated_at
`

type UpdateProjectAssetParams struct {
	ID          pgtype.UUID `json:"id"`
	OrgID       pgtype.Text `json:"org_id"`
	Filename    pgtype.Text `json:"filename"`
	Description pgtype.Text `json:"description"`
	Tags        []string    `json:"tags"`
	Metadata    []byte      `json:"metadata"`
}

type UpdateProjectAssetRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AssetType   string             `json:"asset_type"`
	AssetFormat pgtype.Text        `json:"asset_format"`
	Filename    pgtype.Text        `json:"filename"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProjectAsset(ctx context.Context, arg UpdateProjectAssetParams) (UpdateProjectAssetRow, error) {
	row := q.db.QueryRow(ctx, updateProjectAsset,
		arg.ID,
		arg.OrgID,
		arg.Filename,
		arg.Description,
		arg.Tags,
		arg.Metadata,
	)
	var i UpdateProjectAssetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AssetType,
		&i.AssetFormat,
		&i.Filename,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
