// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dialogues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDialogue = `-- name: CreateDialogue :one
INSERT INTO dialogues (scene_id, character_id, language, text, order_index, hume_voice_id, org_id, emotion_name, emotion_x, emotion_y)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, scene_id, character_id, language, text, translated_text, hume_voice_id, audio_url,
          start_time_seconds, duration_seconds, order_index, emotion_name, emotion_x, emotion_y,
          created_at, updated_at
`

type CreateDialogueParams struct {
	SceneID     pgtype.UUID   `json:"scene_id"`
	CharacterID pgtype.UUID   `json:"character_id"`
	Language    string        `json:"language"`
	Text        string        `json:"text"`
	OrderIndex  pgtype.Int4   `json:"order_index"`
	HumeVoiceID pgtype.Text   `json:"hume_voice_id"`
	OrgID       pgtype.Text   `json:"org_id"`
	EmotionName pgtype.Text   `json:"emotion_name"`
	EmotionX    pgtype.Float8 `json:"emotion_x"`
	EmotionY    pgtype.Float8 `json:"emotion_y"`
}

type CreateDialogueRow struct {
	ID               pgtype.UUID        `json:"id"`
	SceneID          pgtype.UUID        `json:"scene_id"`
	CharacterID      pgtype.UUID        `json:"character_id"`
	Language         string             `json:"language"`
	Text             string             `json:"text"`
	TranslatedText   []byte             `json:"translated_text"`
	HumeVoiceID      pgtype.Text        `json:"hume_voice_id"`
	AudioUrl         pgtype.Text        `json:"audio_url"`
	StartTimeSeconds pgtype.Numeric     `json:"start_time_seconds"`
	DurationSeconds  pgtype.Numeric     `json:"duration_seconds"`
	OrderIndex       pgtype.Int4        `json:"order_index"`
	EmotionName      pgtype.Text        `json:"emotion_name"`
	EmotionX         pgtype.Float8      `json:"emotion_x"`
	EmotionY         pgtype.Float8      `json:"emotion_y"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDialogue(ctx context.Context, arg CreateDialogueParams) (CreateDialogueRow, error) {
	row := q.db.QueryRow(ctx, createDialogue,
		arg.SceneID,
		arg.CharacterID,
		arg.Language,
		arg.Text,
		arg.OrderIndex,
		arg.HumeVoiceID,
		arg.OrgID,
		arg.EmotionName,
		arg.EmotionX,
		arg.EmotionY,
	)
	var i CreateDialogueRow
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.CharacterID,
		&i.Language,
		&i.Text,
		&i.TranslatedText,
		&i.HumeVoiceID,
		&i.AudioUrl,
		&i.StartTimeSeconds,
		&i.DurationSeconds,
		&i.OrderIndex,
		&i.EmotionName,
		&i.EmotionX,
		&i.EmotionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDialogue = `-- name: DeleteDialogue :exec
DELETE FROM dialogues WHERE id = $1
`

func (q *Queries) DeleteDialogue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDialogue, id)
	return err
}

const getDialogue = `-- name: GetDialogue :one
SELECT id, scene_id, character_id, language, text, translated_text, hume_voice_id, audio_url,
       start_time_seconds, duration_seconds, order_index, emotion_name, emotion_x, emotion_y,
       created_at, updated_at
FROM dialogues
WHERE id = $1
`

type GetDialogueRow struct {
	ID               pgtype.UUID        `json:"id"`
	SceneID          pgtype.UUID        `json:"scene_id"`
	CharacterID      pgtype.UUID        `json:"character_id"`
	Language         string             `json:"language"`
	Text             string             `json:"text"`
	TranslatedText   []byte             `json:"translated_text"`
	HumeVoiceID      pgtype.Text        `json:"hume_voice_id"`
	AudioUrl         pgtype.Text        `json:"audio_url"`
	StartTimeSeconds pgtype.Numeric     `json:"start_time_seconds"`
	DurationSeconds  pgtype.Numeric     `json:"duration_seconds"`
	OrderIndex       pgtype.Int4        `json:"order_index"`
	EmotionName      pgtype.Text        `json:"emotion_name"`
	EmotionX         pgtype.Float8      `json:"emotion_x"`
	EmotionY         pgtype.Float8      `json:"emotion_y"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDialogue(ctx context.Context, id pgtype.UUID) (GetDialogueRow, error) {
	row := q.db.QueryRow(ctx, getDialogue, id)
	var i GetDialogueRow
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.CharacterID,
		&i.Language,
		&i.Text,
		&i.TranslatedText,
		&i.HumeVoiceID,
		&i.AudioUrl,
		&i.StartTimeSeconds,
		&i.DurationSeconds,
		&i.OrderIndex,
		&i.EmotionName,
		&i.EmotionX,
		&i.EmotionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDialogueAudioData = `-- name: GetDialogueAudioData :one
SELECT audio_data FROM dialogues WHERE id = $1 AND audio_data IS NOT NULL
`

func (q *Queries) GetDialogueAudioData(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDialogueAudioData, id)
	var audio_data []byte
	err := row.Scan(&audio_data)
	return audio_data, err
}

const getMaxDialogueOrderIndex = `-- name: GetMaxDialogueOrderIndex :one
SELECT COALESCE(MAX(order_index), -1) FROM dialogues WHERE scene_id = $1
`

func (q *Queries) GetMaxDialogueOrderIndex(ctx context.Context, sceneID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxDialogueOrderIndex, sceneID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listDialogues = `-- name: ListDialogues :many
SELECT id, scene_id, character_id, language, text, translated_text, hume_voice_id, audio_url,
       start_time_seconds, duration_seconds, order_index, emotion_name, emotion_x, emotion_y,
       created_at, updated_at
FROM dialogues
WHERE scene_id = $1
ORDER BY order_index ASC, created_at ASC
`

type ListDialoguesRow struct {
	ID               pgtype.UUID        `json:"id"`
	SceneID          pgtype.UUID        `json:"scene_id"`
	CharacterID      pgtype.UUID        `json:"character_id"`
	Language         string             `json:"language"`
	Text             string             `json:"text"`
	TranslatedText   []byte             `json:"translated_text"`
	HumeVoiceID      pgtype.Text        `json:"hume_voice_id"`
	AudioUrl         pgtype.Text        `json:"audio_url"`
	StartTimeSeconds pgtype.Numeric     `json:"start_time_seconds"`
	DurationSeconds  pgtype.Numeric     `json:"duration_seconds"`
	OrderIndex       pgtype.Int4        `json:"order_index"`
	EmotionName      pgtype.Text        `json:"emotion_name"`
	EmotionX         pgtype.Float8      `json:"emotion_x"`
	EmotionY         pgtype.Float8      `json:"emotion_y"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDialogues(ctx context.Context, sceneID pgtype.UUID) ([]ListDialoguesRow, error) {
	rows, err := q.db.Query(ctx, listDialogues, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDialoguesRow
	for rows.Next() {
		var i ListDialoguesRow
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.CharacterID,
			&i.Language,
			&i.Text,
			&i.TranslatedText,
			&i.HumeVoiceID,
			&i.AudioUrl,
			&i.StartTimeSeconds,
			&i.DurationSeconds,
			&i.OrderIndex,
			&i.EmotionName,
			&i.EmotionX,
			&i.EmotionY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDialogue = `-- name: UpdateDialogue :one
UPDATE dialogues
SET text = COALESCE($2, text),
    order_index = COALESCE($3, order_index),
    hume_voice_id = COALESCE($4, hume_voice_id),
    emotion_name = COALESCE($5, emotion_name),
    emotion_x = COALESCE($6, emotion_x),
    emotion_y = COALESCE($7, emotion_y),
    updated_at = NOW()
WHERE id = $1
RETURNING id, scene_id, character_id, language, text, translated_text, hume_voice_id, audio_url,
          start_time_seconds, duration_seconds, order_index, emotion_name, emotion_x, emotion_y,
          created_at, updated_at
`

type UpdateDialogueParams struct {
	ID          pgtype.UUID   `json:"id"`
	Text        string        `json:"text"`
	OrderIndex  pgtype.Int4   `json:"order_index"`
	HumeVoiceID pgtype.Text   `json:"hume_voice_id"`
	EmotionName pgtype.Text   `json:"emotion_name"`
	EmotionX    pgtype.Float8 `json:"emotion_x"`
	EmotionY    pgtype.Float8 `json:"emotion_y"`
}

type UpdateDialogueRow struct {
	ID               pgtype.UUID        `json:"id"`
	SceneID          pgtype.UUID        `json:"scene_id"`
	CharacterID      pgtype.UUID        `json:"character_id"`
	Language         string             `json:"language"`
	Text             string             `json:"text"`
	TranslatedText   []byte             `json:"translated_text"`
	HumeVoiceID      pgtype.Text        `json:"hume_voice_id"`
	AudioUrl         pgtype.Text        `json:"audio_url"`
	StartTimeSeconds pgtype.Numeric     `json:"start_time_seconds"`
	DurationSeconds  pgtype.Numeric     `json:"duration_seconds"`
	OrderIndex       pgtype.Int4        `json:"order_index"`
	EmotionName      pgtype.Text        `json:"emotion_name"`
	EmotionX         pgtype.Float8      `json:"emotion_x"`
	EmotionY         pgtype.Float8      `json:"emotion_y"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateDialogue(ctx context.Context, arg UpdateDialogueParams) (UpdateDialogueRow, error) {
	row := q.db.QueryRow(ctx, updateDialogue,
		arg.ID,
		arg.Text,
		arg.OrderIndex,
		arg.HumeVoiceID,
		arg.EmotionName,
		arg.EmotionX,
		arg.EmotionY,
	)
	var i UpdateDialogueRow
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.CharacterID,
		&i.Language,
		&i.Text,
		&i.TranslatedText,
		&i.HumeVoiceID,
		&i.AudioUrl,
		&i.StartTimeSeconds,
		&i.DurationSeconds,
		&i.OrderIndex,
		&i.EmotionName,
		&i.EmotionX,
		&i.EmotionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDialogueAudio = `-- name: UpdateDialogueAudio :one
UPDATE dialogues
SET audio_data = $2,
    audio_url = $3,
    duration_seconds = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, scene_id, character_id, language, text, translated_text, hume_voice_id, audio_url,
          start_time_seconds, duration_seconds, order_index, emotion_name, emotion_x, emotion_y,
          created_at, updated_at
`

type UpdateDialogueAudioParams struct {
	ID              pgtype.UUID    `json:"id"`
	AudioData       []byte         `json:"audio_data"`
	AudioUrl        pgtype.Text    `json:"audio_url"`
	DurationSeconds pgtype.Numeric `json:"duration_seconds"`
}

type UpdateDialogueAudioRow struct {
	ID               pgtype.UUID        `json:"id"`
	SceneID          pgtype.UUID        `json:"scene_id"`
	CharacterID      pgtype.UUID        `json:"character_id"`
	Language         string             `json:"language"`
	Text             string             `json:"text"`
	TranslatedText   []byte             `json:"translated_text"`
	HumeVoiceID      pgtype.Text        `json:"hume_voice_id"`
	AudioUrl         pgtype.Text        `json:"audio_url"`
	StartTimeSeconds pgtype.Numeric     `json:"start_time_seconds"`
	DurationSeconds  pgtype.Numeric     `json:"duration_seconds"`
	OrderIndex       pgtype.Int4        `json:"order_index"`
	EmotionName      pgtype.Text        `json:"emotion_name"`
	EmotionX         pgtype.Float8      `json:"emotion_x"`
	EmotionY         pgtype.Float8      `json:"emotion_y"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateDialogueAudio(ctx context.Context, arg UpdateDialogueAudioParams) (UpdateDialogueAudioRow, error) {
	row := q.db.QueryRow(ctx, updateDialogueAudio,
		arg.ID,
		arg.AudioData,
		arg.AudioUrl,
		arg.DurationSeconds,
	)
	var i UpdateDialogueAudioRow
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.CharacterID,
		&i.Language,
		&i.Text,
		&i.TranslatedText,
		&i.HumeVoiceID,
		&i.AudioUrl,
		&i.StartTimeSeconds,
		&i.DurationSeconds,
		&i.OrderIndex,
		&i.EmotionName,
		&i.EmotionX,
		&i.EmotionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
