// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emotion_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmotionProfile = `-- name: GetEmotionProfile :one
SELECT id, node_id, node_type, joy, sadness, fear, anger, surprise, trust, anticipation, disgust, relief, hope, emotion_vector_json, created_at, updated_at
FROM emotion_profiles
WHERE node_id = $1 AND node_type = $2
`

type GetEmotionProfileParams struct {
	NodeID   pgtype.UUID `json:"node_id"`
	NodeType string      `json:"node_type"`
}

func (q *Queries) GetEmotionProfile(ctx context.Context, arg GetEmotionProfileParams) (EmotionProfile, error) {
	row := q.db.QueryRow(ctx, getEmotionProfile, arg.NodeID, arg.NodeType)
	var i EmotionProfile
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NodeType,
		&i.Joy,
		&i.Sadness,
		&i.Fear,
		&i.Anger,
		&i.Surprise,
		&i.Trust,
		&i.Anticipation,
		&i.Disgust,
		&i.Relief,
		&i.Hope,
		&i.EmotionVectorJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmotionProfile = `-- name: UpsertEmotionProfile :one
INSERT INTO emotion_profiles (node_id, node_type, joy, sadness, fear, anger, surprise, trust, anticipation, disgust, relief, hope, emotion_vector_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (node_id, node_type) DO UPDATE
SET joy = EXCLUDED.joy,
    sadness = EXCLUDED.sadness,
    fear = EXCLUDED.fear,
    anger = EXCLUDED.anger,
    surprise = EXCLUDED.surprise,
    trust = EXCLUDED.trust,
    anticipation = EXCLUDED.anticipation,
    disgust = EXCLUDED.disgust,
    relief = EXCLUDED.relief,
    hope = EXCLUDED.hope,
    emotion_vector_json = EXCLUDED.emotion_vector_json,
    updated_at = NOW()
RETURNING id, node_id, node_type, joy, sadness, fear, anger, surprise, trust, anticipation, disgust, relief, hope, emotion_vector_json, created_at, updated_at
`

type UpsertEmotionProfileParams struct {
	NodeID            pgtype.UUID   `json:"node_id"`
	NodeType          string        `json:"node_type"`
	Joy               pgtype.Float8 `json:"joy"`
	Sadness           pgtype.Float8 `json:"sadness"`
	Fear              pgtype.Float8 `json:"fear"`
	Anger             pgtype.Float8 `json:"anger"`
	Surprise          pgtype.Float8 `json:"surprise"`
	Trust             pgtype.Float8 `json:"trust"`
	Anticipation      pgtype.Float8 `json:"anticipation"`
	Disgust           pgtype.Float8 `json:"disgust"`
	Relief            pgtype.Float8 `json:"relief"`
	Hope              pgtype.Float8 `json:"hope"`
	EmotionVectorJson []byte        `json:"emotion_vector_json"`
}

func (q *Queries) UpsertEmotionProfile(ctx context.Context, arg UpsertEmotionProfileParams) (EmotionProfile, error) {
	row := q.db.QueryRow(ctx, upsertEmotionProfile,
		arg.NodeID,
		arg.NodeType,
		arg.Joy,
		arg.Sadness,
		arg.Fear,
		arg.Anger,
		arg.Surprise,
		arg.Trust,
		arg.Anticipation,
		arg.Disgust,
		arg.Relief,
		arg.Hope,
		arg.EmotionVectorJson,
	)
	var i EmotionProfile
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.NodeType,
		&i.Joy,
		&i.Sadness,
		&i.Fear,
		&i.Anger,
		&i.Surprise,
		&i.Trust,
		&i.Anticipation,
		&i.Disgust,
		&i.Relief,
		&i.Hope,
		&i.EmotionVectorJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
