// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generated_images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGeneratedImage = `-- name: CreateGeneratedImage :one
INSERT INTO generated_images (scene_id, provider, external_image_id, image_data, image_format, image_type, prompt, model, character_id, org_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, scene_id, provider, external_image_id, image_format, image_type, prompt, model, character_id, created_at
`

type CreateGeneratedImageParams struct {
	SceneID         pgtype.UUID `json:"scene_id"`
	Provider        pgtype.Text `json:"provider"`
	ExternalImageID pgtype.Text `json:"external_image_id"`
	ImageData       []byte      `json:"image_data"`
	ImageFormat     pgtype.Text `json:"image_format"`
	ImageType       pgtype.Text `json:"image_type"`
	Prompt          pgtype.Text `json:"prompt"`
	Model           pgtype.Text `json:"model"`
	CharacterID     pgtype.UUID `json:"character_id"`
	OrgID           pgtype.Text `json:"org_id"`
}

type CreateGeneratedImageRow struct {
	ID              pgtype.UUID        `json:"id"`
	SceneID         pgtype.UUID        `json:"scene_id"`
	Provider        pgtype.Text        `json:"provider"`
	ExternalImageID pgtype.Text        `json:"external_image_id"`
	ImageFormat     pgtype.Text        `json:"image_format"`
	ImageType       pgtype.Text        `json:"image_type"`
	Prompt          pgtype.Text        `json:"prompt"`
	Model           pgtype.Text        `json:"model"`
	CharacterID     pgtype.UUID        `json:"character_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGeneratedImage(ctx context.Context, arg CreateGeneratedImageParams) (CreateGeneratedImageRow, error) {
	row := q.db.QueryRow(ctx, createGeneratedImage,
		arg.SceneID,
		arg.Provider,
		arg.ExternalImageID,
		arg.ImageData,
		arg.ImageFormat,
		arg.ImageType,
		arg.Prompt,
		arg.Model,
		arg.CharacterID,
		arg.OrgID,
	)
	var i CreateGeneratedImageRow
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.Provider,
		&i.ExternalImageID,
		&i.ImageFormat,
		&i.ImageType,
		&i.Prompt,
		&i.Model,
		&i.CharacterID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGeneratedImage = `-- name: DeleteGeneratedImage :exec
DELETE FROM generated_images WHERE id = $1
`

func (q *Queries) DeleteGeneratedImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGeneratedImage, id)
	return err
}

const getGeneratedImage = `-- name: GetGeneratedImage :one
SELECT id, scene_id, provider, external_image_id, image_format, image_type, prompt, model, character_id, created_at
FROM generated_images
WHERE id = $1
`

type GetGeneratedImageRow struct {
	ID              pgtype.UUID        `json:"id"`
	SceneID         pgtype.UUID        `json:"scene_id"`
	Provider        pgtype.Text        `json:"provider"`
	ExternalImageID pgtype.Text        `json:"external_image_id"`
	ImageFormat     pgtype.Text        `json:"image_format"`
	ImageType       pgtype.Text        `json:"image_type"`
	Prompt          pgtype.Text        `json:"prompt"`
	Model           pgtype.Text        `json:"model"`
	CharacterID     pgtype.UUID        `json:"character_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGeneratedImage(ctx context.Context, id pgtype.UUID) (GetGeneratedImageRow, error) {
	row := q.db.QueryRow(ctx, getGeneratedImage, id)
	var i GetGeneratedImageRow
	err := row.Scan(
		&i.ID,
		&i.SceneID,
		&i.Provider,
		&i.ExternalImageID,
		&i.ImageFormat,
		&i.ImageType,
		&i.Prompt,
		&i.Model,
		&i.CharacterID,
		&i.CreatedAt,
	)
	return i, err
}

const getGeneratedImageData = `-- name: GetGeneratedImageData :one
SELECT image_data, image_format FROM generated_images WHERE id = $1
`

type GetGeneratedImageDataRow struct {
	ImageData   []byte      `json:"image_data"`
	ImageFormat pgtype.Text `json:"image_format"`
}

func (q *Queries) GetGeneratedImageData(ctx context.Context, id pgtype.UUID) (GetGeneratedImageDataRow, error) {
	row := q.db.QueryRow(ctx, getGeneratedImageData, id)
	var i GetGeneratedImageDataRow
	err := row.Scan(&i.ImageData, &i.ImageFormat)
	return i, err
}

const listGeneratedImages = `-- name: ListGeneratedImages :many
SELECT id, scene_id, provider, external_image_id, image_format, image_type, prompt, model, character_id, created_at
FROM generated_images
WHERE scene_id = $1
ORDER BY created_at DESC
`

type ListGeneratedImagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	SceneID         pgtype.UUID        `json:"scene_id"`
	Provider        pgtype.Text        `json:"provider"`
	ExternalImageID pgtype.Text        `json:"external_image_id"`
	ImageFormat     pgtype.Text        `json:"image_format"`
	ImageType       pgtype.Text        `json:"image_type"`
	Prompt          pgtype.Text        `json:"prompt"`
	Model           pgtype.Text        `json:"model"`
	CharacterID     pgtype.UUID        `json:"character_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGeneratedImages(ctx context.Context, sceneID pgtype.UUID) ([]ListGeneratedImagesRow, error) {
	rows, err := q.db.Query(ctx, listGeneratedImages, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGeneratedImagesRow
	for rows.Next() {
		var i ListGeneratedImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.Provider,
			&i.ExternalImageID,
			&i.ImageFormat,
			&i.ImageType,
			&i.Prompt,
			&i.Model,
			&i.CharacterID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneratedImagesByCharacter = `-- name: ListGeneratedImagesByCharacter :many
SELECT id, scene_id, provider, external_image_id, image_format, image_type, prompt, model, character_id, created_at
FROM generated_images
WHERE character_id = $1
ORDER BY created_at DESC
`

type ListGeneratedImagesByCharacterRow struct {
	ID              pgtype.UUID        `json:"id"`
	SceneID         pgtype.UUID        `json:"scene_id"`
	Provider        pgtype.Text        `json:"provider"`
	ExternalImageID pgtype.Text        `json:"external_image_id"`
	ImageFormat     pgtype.Text        `json:"image_format"`
	ImageType       pgtype.Text        `json:"image_type"`
	Prompt          pgtype.Text        `json:"prompt"`
	Model           pgtype.Text        `json:"model"`
	CharacterID     pgtype.UUID        `json:"character_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGeneratedImagesByCharacter(ctx context.Context, characterID pgtype.UUID) ([]ListGeneratedImagesByCharacterRow, error) {
	rows, err := q.db.Query(ctx, listGeneratedImagesByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGeneratedImagesByCharacterRow
	for rows.Next() {
		var i ListGeneratedImagesByCharacterRow
		if err := rows.Scan(
			&i.ID,
			&i.SceneID,
			&i.Provider,
			&i.ExternalImageID,
			&i.ImageFormat,
			&i.ImageType,
			&i.Prompt,
			&i.Model,
			&i.CharacterID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
