// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manga_generated_images.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMangaGeneratedImage = `-- name: CreateMangaGeneratedImage :one
INSERT INTO manga_generated_images (manga_project_id, panel_id, image_data, image_format, width, height, prompt, model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, manga_project_id, panel_id, image_data, image_format, width, height, prompt, model, created_at
`

type CreateMangaGeneratedImageParams struct {
	MangaProjectID pgtype.UUID `json:"manga_project_id"`
	PanelID        pgtype.UUID `json:"panel_id"`
	ImageData      []byte      `json:"image_data"`
	ImageFormat    string      `json:"image_format"`
	Width          pgtype.Int4 `json:"width"`
	Height         pgtype.Int4 `json:"height"`
	Prompt         pgtype.Text `json:"prompt"`
	Model          pgtype.Text `json:"model"`
}

func (q *Queries) CreateMangaGeneratedImage(ctx context.Context, arg CreateMangaGeneratedImageParams) (MangaGeneratedImage, error) {
	row := q.db.QueryRow(ctx, createMangaGeneratedImage,
		arg.MangaProjectID,
		arg.PanelID,
		arg.ImageData,
		arg.ImageFormat,
		arg.Width,
		arg.Height,
		arg.Prompt,
		arg.Model,
	)
	var i MangaGeneratedImage
	err := row.Scan(
		&i.ID,
		&i.MangaProjectID,
		&i.PanelID,
		&i.ImageData,
		&i.ImageFormat,
		&i.Width,
		&i.Height,
		&i.Prompt,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getMangaGeneratedImage = `-- name: GetMangaGeneratedImage :one
SELECT id, manga_project_id, panel_id, image_data, image_format, width, height, prompt, model, created_at
FROM manga_generated_images
WHERE id = $1
`

func (q *Queries) GetMangaGeneratedImage(ctx context.Context, id pgtype.UUID) (MangaGeneratedImage, error) {
	row := q.db.QueryRow(ctx, getMangaGeneratedImage, id)
	var i MangaGeneratedImage
	err := row.Scan(
		&i.ID,
		&i.MangaProjectID,
		&i.PanelID,
		&i.ImageData,
		&i.ImageFormat,
		&i.Width,
		&i.Height,
		&i.Prompt,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const listMangaGeneratedImages = `-- name: ListMangaGeneratedImages :many
SELECT id, manga_project_id, panel_id, image_data, image_format, width, height, prompt, model, created_at
FROM manga_generated_images
WHERE manga_project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMangaGeneratedImages(ctx context.Context, mangaProjectID pgtype.UUID) ([]MangaGeneratedImage, error) {
	rows, err := q.db.Query(ctx, listMangaGeneratedImages, mangaProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MangaGeneratedImage
	for rows.Next() {
		var i MangaGeneratedImage
		if err := rows.Scan(
			&i.ID,
			&i.MangaProjectID,
			&i.PanelID,
			&i.ImageData,
			&i.ImageFormat,
			&i.Width,
			&i.Height,
			&i.Prompt,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
