// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operation_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperationHistory = `-- name: CreateOperationHistory :one
INSERT INTO operation_history (entity_type, entity_id, operation_type, operation_data, user_id, org_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entity_type, entity_id, operation_type, operation_data, user_id, created_at
`

type CreateOperationHistoryParams struct {
	EntityType    string      `json:"entity_type"`
	EntityID      pgtype.UUID `json:"entity_id"`
	OperationType string      `json:"operation_type"`
	OperationData []byte      `json:"operation_data"`
	UserID        pgtype.UUID `json:"user_id"`
	OrgID         pgtype.Text `json:"org_id"`
}

type CreateOperationHistoryRow struct {
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	OperationType string             `json:"operation_type"`
	OperationData []byte             `json:"operation_data"`
	UserID        pgtype.UUID        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOperationHistory(ctx context.Context, arg CreateOperationHistoryParams) (CreateOperationHistoryRow, error) {
	row := q.db.QueryRow(ctx, createOperationHistory,
		arg.EntityType,
		arg.EntityID,
		arg.OperationType,
		arg.OperationData,
		arg.UserID,
		arg.OrgID,
	)
	var i CreateOperationHistoryRow
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.OperationType,
		&i.OperationData,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listOperationHistory = `-- name: ListOperationHistory :many
SELECT id, entity_type, entity_id, operation_type, operation_data, user_id, created_at
FROM operation_history
ORDER BY created_at DESC
LIMIT 100
`

type ListOperationHistoryRow struct {
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	OperationType string             `json:"operation_type"`
	OperationData []byte             `json:"operation_data"`
	UserID        pgtype.UUID        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOperationHistory(ctx context.Context) ([]ListOperationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listOperationHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOperationHistoryRow
	for rows.Next() {
		var i ListOperationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.OperationType,
			&i.OperationData,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationHistoryByEntity = `-- name: ListOperationHistoryByEntity :many
SELECT id, entity_type, entity_id, operation_type, operation_data, user_id, created_at
FROM operation_history
WHERE entity_id = $1 AND ($2::text IS NULL OR entity_type = $2)
ORDER BY created_at DESC
LIMIT 100
`

type ListOperationHistoryByEntityParams struct {
	EntityID pgtype.UUID `json:"entity_id"`
	Column2  string      `json:"column_2"`
}

type ListOperationHistoryByEntityRow struct {
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	OperationType string             `json:"operation_type"`
	OperationData []byte             `json:"operation_data"`
	UserID        pgtype.UUID        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOperationHistoryByEntity(ctx context.Context, arg ListOperationHistoryByEntityParams) ([]ListOperationHistoryByEntityRow, error) {
	rows, err := q.db.Query(ctx, listOperationHistoryByEntity, arg.EntityID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOperationHistoryByEntityRow
	for rows.Next() {
		var i ListOperationHistoryByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.OperationType,
			&i.OperationData,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationHistoryByType = `-- name: ListOperationHistoryByType :many
SELECT id, entity_type, entity_id, operation_type, operation_data, user_id, created_at
FROM operation_history
WHERE entity_type = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListOperationHistoryByTypeRow struct {
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	OperationType string             `json:"operation_type"`
	OperationData []byte             `json:"operation_data"`
	UserID        pgtype.UUID        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOperationHistoryByType(ctx context.Context, entityType string) ([]ListOperationHistoryByTypeRow, error) {
	rows, err := q.db.Query(ctx, listOperationHistoryByType, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOperationHistoryByTypeRow
	for rows.Next() {
		var i ListOperationHistoryByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.OperationType,
			&i.OperationData,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
