// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserPermission = `-- name: CheckUserPermission :one
SELECT MAX(rp.level) as max_level
FROM role_permissions rp
JOIN project_team_assignments pta ON pta.role_id = rp.role_id
JOIN team_members tm ON tm.id = pta.team_member_id
WHERE pta.project_id = $1 
  AND tm.user_id = $2 
  AND rp.scope = $3
`

type CheckUserPermissionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
	Scope     string      `json:"scope"`
}

func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, checkUserPermission, arg.ProjectID, arg.UserID, arg.Scope)
	var max_level interface{}
	err := row.Scan(&max_level)
	return max_level, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, name_ja, type, display_order)
VALUES ($1, $2, $3, $4)
RETURNING id, name, name_ja, type, display_order, created_at
`

type CreateDepartmentParams struct {
	Name         string `json:"name"`
	NameJa       string `json:"name_ja"`
	Type         string `json:"type"`
	DisplayOrder int32  `json:"display_order"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.Name,
		arg.NameJa,
		arg.Type,
		arg.DisplayOrder,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameJa,
		&i.Type,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectTeamAssignment = `-- name: CreateProjectTeamAssignment :one
INSERT INTO project_team_assignments (project_id, team_member_id, role_id, episode_id)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, team_member_id, role_id, episode_id, assigned_at
`

type CreateProjectTeamAssignmentParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	TeamMemberID pgtype.UUID `json:"team_member_id"`
	RoleID       pgtype.UUID `json:"role_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
}

func (q *Queries) CreateProjectTeamAssignment(ctx context.Context, arg CreateProjectTeamAssignmentParams) (ProjectTeamAssignment, error) {
	row := q.db.QueryRow(ctx, createProjectTeamAssignment,
		arg.ProjectID,
		arg.TeamMemberID,
		arg.RoleID,
		arg.EpisodeID,
	)
	var i ProjectTeamAssignment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TeamMemberID,
		&i.RoleID,
		&i.EpisodeID,
		&i.AssignedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (department_id, name, name_ja, description, display_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, department_id, name, name_ja, description, display_order, created_at
`

type CreateRoleParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	Name         string      `json:"name"`
	NameJa       string      `json:"name_ja"`
	Description  pgtype.Text `json:"description"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.DepartmentID,
		arg.Name,
		arg.NameJa,
		arg.Description,
		arg.DisplayOrder,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Name,
		&i.NameJa,
		&i.Description,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permissions (role_id, scope, level)
VALUES ($1, $2, $3)
RETURNING id, role_id, scope, level, created_at
`

type CreateRolePermissionParams struct {
	RoleID pgtype.UUID `json:"role_id"`
	Scope  string      `json:"scope"`
	Level  int32       `json:"level"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, createRolePermission, arg.RoleID, arg.Scope, arg.Level)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Scope,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectTeamAssignment = `-- name: DeleteProjectTeamAssignment :exec
DELETE FROM project_team_assignments
WHERE id = $1
`

func (q *Queries) DeleteProjectTeamAssignment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectTeamAssignment, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, name_ja, type, display_order, created_at
FROM departments
WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameJa,
		&i.Type,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectTeamAssignment = `-- name: GetProjectTeamAssignment :one
SELECT id, project_id, team_member_id, role_id, episode_id, assigned_at
FROM project_team_assignments
WHERE id = $1
`

func (q *Queries) GetProjectTeamAssignment(ctx context.Context, id pgtype.UUID) (ProjectTeamAssignment, error) {
	row := q.db.QueryRow(ctx, getProjectTeamAssignment, id)
	var i ProjectTeamAssignment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TeamMemberID,
		&i.RoleID,
		&i.EpisodeID,
		&i.AssignedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, department_id, name, name_ja, description, display_order, created_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.Name,
		&i.NameJa,
		&i.Description,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getRolePermissionsByRoleIds = `-- name: GetRolePermissionsByRoleIds :many
SELECT id, role_id, scope, level, created_at
FROM role_permissions
WHERE role_id = ANY($1::uuid[])
`

func (q *Queries) GetRolePermissionsByRoleIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, getRolePermissionsByRoleIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Scope,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, org_id, user_id, name, email, avatar_url, created_at
FROM team_members
WHERE id = $1
`

func (q *Queries) GetTeamMember(ctx context.Context, id pgtype.UUID) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMemberByUserId = `-- name: GetTeamMemberByUserId :one
SELECT id, org_id, user_id, name, email, avatar_url, created_at
FROM team_members
WHERE org_id = $1 AND user_id = $2
`

type GetTeamMemberByUserIdParams struct {
	OrgID  string `json:"org_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTeamMemberByUserId(ctx context.Context, arg GetTeamMemberByUserIdParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByUserId, arg.OrgID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissionsInProject = `-- name: GetUserPermissionsInProject :many
SELECT rp.id, rp.role_id, rp.scope, rp.level, rp.created_at
FROM role_permissions rp
JOIN project_team_assignments pta ON pta.role_id = rp.role_id
JOIN team_members tm ON tm.id = pta.team_member_id
WHERE pta.project_id = $1 AND tm.user_id = $2
`

type GetUserPermissionsInProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) GetUserPermissionsInProject(ctx context.Context, arg GetUserPermissionsInProjectParams) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsInProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Scope,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesInProject = `-- name: GetUserRolesInProject :many
SELECT r.id, r.department_id, r.name, r.name_ja, r.description, r.display_order, r.created_at
FROM roles r
JOIN project_team_assignments pta ON pta.role_id = r.id
JOIN team_members tm ON tm.id = pta.team_member_id
WHERE pta.project_id = $1 AND tm.user_id = $2
`

type GetUserRolesInProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) GetUserRolesInProject(ctx context.Context, arg GetUserRolesInProjectParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRolesInProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.Name,
			&i.NameJa,
			&i.Description,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, name_ja, type, display_order, created_at
FROM departments
ORDER BY display_order, name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameJa,
			&i.Type,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTeamAssignments = `-- name: ListProjectTeamAssignments :many
SELECT 
  pta.id, pta.project_id, pta.team_member_id, pta.role_id, pta.episode_id, pta.assigned_at,
  tm.id as member_id, tm.org_id, tm.user_id, tm.name as member_name, tm.email, tm.avatar_url, tm.created_at as member_created_at,
  r.id as role_db_id, r.department_id, r.name as role_name, r.name_ja as role_name_ja, r.description as role_description, r.display_order as role_display_order, r.created_at as role_created_at
FROM project_team_assignments pta
JOIN team_members tm ON tm.id = pta.team_member_id
JOIN roles r ON r.id = pta.role_id
WHERE pta.project_id = $1
  AND ($2::uuid IS NULL OR pta.episode_id = $2)
ORDER BY r.display_order, tm.name
`

type ListProjectTeamAssignmentsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   pgtype.UUID `json:"column_2"`
}

type ListProjectTeamAssignmentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	TeamMemberID     pgtype.UUID        `json:"team_member_id"`
	RoleID           pgtype.UUID        `json:"role_id"`
	EpisodeID        pgtype.UUID        `json:"episode_id"`
	AssignedAt       pgtype.Timestamptz `json:"assigned_at"`
	MemberID         pgtype.UUID        `json:"member_id"`
	OrgID            string             `json:"org_id"`
	UserID           string             `json:"user_id"`
	MemberName       string             `json:"member_name"`
	Email            pgtype.Text        `json:"email"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	MemberCreatedAt  pgtype.Timestamptz `json:"member_created_at"`
	RoleDbID         pgtype.UUID        `json:"role_db_id"`
	DepartmentID     pgtype.UUID        `json:"department_id"`
	RoleName         string             `json:"role_name"`
	RoleNameJa       string             `json:"role_name_ja"`
	RoleDescription  pgtype.Text        `json:"role_description"`
	RoleDisplayOrder int32              `json:"role_display_order"`
	RoleCreatedAt    pgtype.Timestamptz `json:"role_created_at"`
}

func (q *Queries) ListProjectTeamAssignments(ctx context.Context, arg ListProjectTeamAssignmentsParams) ([]ListProjectTeamAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectTeamAssignments, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTeamAssignmentsRow
	for rows.Next() {
		var i ListProjectTeamAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TeamMemberID,
			&i.RoleID,
			&i.EpisodeID,
			&i.AssignedAt,
			&i.MemberID,
			&i.OrgID,
			&i.UserID,
			&i.MemberName,
			&i.Email,
			&i.AvatarUrl,
			&i.MemberCreatedAt,
			&i.RoleDbID,
			&i.DepartmentID,
			&i.RoleName,
			&i.RoleNameJa,
			&i.RoleDescription,
			&i.RoleDisplayOrder,
			&i.RoleCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT id, role_id, scope, level, created_at
FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Scope,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, department_id, name, name_ja, description, display_order, created_at
FROM roles
WHERE ($1::uuid IS NULL OR department_id = $1)
ORDER BY display_order, name
`

func (q *Queries) ListRoles(ctx context.Context, dollar_1 pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.Name,
			&i.NameJa,
			&i.Description,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT id, org_id, user_id, name, email, avatar_url, created_at
FROM team_members
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListTeamMembers(ctx context.Context, orgID string) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeamMember = `-- name: UpsertTeamMember :one
INSERT INTO team_members (org_id, user_id, name, email, avatar_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, user_id) DO UPDATE
SET name = EXCLUDED.name, email = EXCLUDED.email, avatar_url = EXCLUDED.avatar_url
RETURNING id, org_id, user_id, name, email, avatar_url, created_at
`

type UpsertTeamMemberParams struct {
	OrgID     string      `json:"org_id"`
	UserID    string      `json:"user_id"`
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertTeamMember(ctx context.Context, arg UpsertTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, upsertTeamMember,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
