// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addResourceTag = `-- name: AddResourceTag :exec
INSERT INTO resource_tags (resource_type, resource_id, tag_id, org_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (resource_type, resource_id, tag_id) DO NOTHING
`

type AddResourceTagParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	TagID        pgtype.UUID `json:"tag_id"`
	OrgID        pgtype.Text `json:"org_id"`
}

func (q *Queries) AddResourceTag(ctx context.Context, arg AddResourceTagParams) error {
	_, err := q.db.Exec(ctx, addResourceTag,
		arg.ResourceType,
		arg.ResourceID,
		arg.TagID,
		arg.OrgID,
	)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (project_id, org_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, color, created_at
`

type CreateTagParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	OrgID     pgtype.Text `json:"org_id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
}

type CreateTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ProjectID,
		arg.OrgID,
		arg.Name,
		arg.Color,
	)
	var i CreateTagRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1 AND org_id = $2
`

type DeleteTagParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.OrgID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, project_id, name, color, created_at
FROM tags
WHERE id = $1 AND org_id = $2
`

type GetTagParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
}

type GetTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (GetTagRow, error) {
	row := q.db.QueryRow(ctx, getTag, arg.ID, arg.OrgID)
	var i GetTagRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listResourceTags = `-- name: ListResourceTags :many
SELECT t.id, t.project_id, t.name, t.color, t.created_at
FROM tags t
INNER JOIN resource_tags rt ON t.id = rt.tag_id
WHERE rt.resource_type = $1 AND rt.resource_id = $2 AND rt.org_id = $3
ORDER BY t.name ASC
`

type ListResourceTagsParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	OrgID        pgtype.Text `json:"org_id"`
}

type ListResourceTagsRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListResourceTags(ctx context.Context, arg ListResourceTagsParams) ([]ListResourceTagsRow, error) {
	rows, err := q.db.Query(ctx, listResourceTags, arg.ResourceType, arg.ResourceID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceTagsRow
	for rows.Next() {
		var i ListResourceTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, project_id, name, color, created_at
FROM tags
WHERE project_id = $1 AND org_id = $2
ORDER BY name ASC
`

type ListTagsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	OrgID     pgtype.Text `json:"org_id"`
}

type ListTagsRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.ProjectID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeResourceTag = `-- name: RemoveResourceTag :exec
DELETE FROM resource_tags
WHERE resource_type = $1 AND resource_id = $2 AND tag_id = $3 AND org_id = $4
`

type RemoveResourceTagParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	TagID        pgtype.UUID `json:"tag_id"`
	OrgID        pgtype.Text `json:"org_id"`
}

func (q *Queries) RemoveResourceTag(ctx context.Context, arg RemoveResourceTagParams) error {
	_, err := q.db.Exec(ctx, removeResourceTag,
		arg.ResourceType,
		arg.ResourceID,
		arg.TagID,
		arg.OrgID,
	)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = COALESCE($3, name),
    color = COALESCE($4, color)
WHERE id = $1 AND org_id = $2
RETURNING id, project_id, name, color, created_at
`

type UpdateTagParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.Text `json:"org_id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

type UpdateTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Color,
	)
	var i UpdateTagRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
