// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalAction = `-- name: CreateApprovalAction :one
INSERT INTO approval_actions (approval_id, reviewer_id, action, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, approval_id, reviewer_id, action, comment, created_at
`

type CreateApprovalActionParams struct {
	ApprovalID pgtype.UUID `json:"approval_id"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
	Action     string      `json:"action"`
	Comment    pgtype.Text `json:"comment"`
}

func (q *Queries) CreateApprovalAction(ctx context.Context, arg CreateApprovalActionParams) (ApprovalAction, error) {
	row := q.db.QueryRow(ctx, createApprovalAction,
		arg.ApprovalID,
		arg.ReviewerID,
		arg.Action,
		arg.Comment,
	)
	var i ApprovalAction
	err := row.Scan(
		&i.ID,
		&i.ApprovalID,
		&i.ReviewerID,
		&i.Action,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO approval_requests (project_id, episode_id, type, submitter_id, resource_id, resource_type, status, workflow_id, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, episode_id, type, submitter_id, resource_id, resource_type, status, workflow_id, run_id, created_at, updated_at
`

type CreateApprovalRequestParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	Type         string      `json:"type"`
	SubmitterID  pgtype.UUID `json:"submitter_id"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	ResourceType string      `json:"resource_type"`
	Status       string      `json:"status"`
	WorkflowID   pgtype.Text `json:"workflow_id"`
	RunID        pgtype.Text `json:"run_id"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createApprovalRequest,
		arg.ProjectID,
		arg.EpisodeID,
		arg.Type,
		arg.SubmitterID,
		arg.ResourceID,
		arg.ResourceType,
		arg.Status,
		arg.WorkflowID,
		arg.RunID,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Type,
		&i.SubmitterID,
		&i.ResourceID,
		&i.ResourceType,
		&i.Status,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEpisodeProduction = `-- name: CreateEpisodeProduction :one
INSERT INTO episode_productions (project_id, episode_id, status, deadline, workflow_id, run_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, episode_id, status, deadline, progress_percent, workflow_id, run_id, created_at, updated_at
`

type CreateEpisodeProductionParams struct {
	ProjectID  pgtype.UUID        `json:"project_id"`
	EpisodeID  pgtype.UUID        `json:"episode_id"`
	Status     string             `json:"status"`
	Deadline   pgtype.Timestamptz `json:"deadline"`
	WorkflowID pgtype.Text        `json:"workflow_id"`
	RunID      pgtype.Text        `json:"run_id"`
}

func (q *Queries) CreateEpisodeProduction(ctx context.Context, arg CreateEpisodeProductionParams) (EpisodeProduction, error) {
	row := q.db.QueryRow(ctx, createEpisodeProduction,
		arg.ProjectID,
		arg.EpisodeID,
		arg.Status,
		arg.Deadline,
		arg.WorkflowID,
		arg.RunID,
	)
	var i EpisodeProduction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Status,
		&i.Deadline,
		&i.ProgressPercent,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, episode_id, title, description, role_id, status, deadline, workflow_id, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, episode_id, title, description, assignee_id, role_id, status, deadline, workflow_id, run_id, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Status      string             `json:"status"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	WorkflowID  pgtype.Text        `json:"workflow_id"`
	RunID       pgtype.Text        `json:"run_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.EpisodeID,
		arg.Title,
		arg.Description,
		arg.RoleID,
		arg.Status,
		arg.Deadline,
		arg.WorkflowID,
		arg.RunID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.RoleID,
		&i.Status,
		&i.Deadline,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, project_id, episode_id, type, submitter_id, resource_id, resource_type, status, workflow_id, run_id, created_at, updated_at
FROM approval_requests
WHERE id = $1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id pgtype.UUID) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Type,
		&i.SubmitterID,
		&i.ResourceID,
		&i.ResourceType,
		&i.Status,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEpisodeProduction = `-- name: GetEpisodeProduction :one
SELECT id, project_id, episode_id, status, deadline, progress_percent, workflow_id, run_id, created_at, updated_at
FROM episode_productions
WHERE project_id = $1 AND episode_id = $2
`

type GetEpisodeProductionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) GetEpisodeProduction(ctx context.Context, arg GetEpisodeProductionParams) (EpisodeProduction, error) {
	row := q.db.QueryRow(ctx, getEpisodeProduction, arg.ProjectID, arg.EpisodeID)
	var i EpisodeProduction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Status,
		&i.Deadline,
		&i.ProgressPercent,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, episode_id, title, description, assignee_id, role_id, status, deadline, workflow_id, run_id, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.RoleID,
		&i.Status,
		&i.Deadline,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalActions = `-- name: ListApprovalActions :many

SELECT id, approval_id, reviewer_id, action, comment, created_at
FROM approval_actions
WHERE approval_id = $1
ORDER BY created_at ASC
`

// Approval Actions
func (q *Queries) ListApprovalActions(ctx context.Context, approvalID pgtype.UUID) ([]ApprovalAction, error) {
	rows, err := q.db.Query(ctx, listApprovalActions, approvalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalAction
	for rows.Next() {
		var i ApprovalAction
		if err := rows.Scan(
			&i.ID,
			&i.ApprovalID,
			&i.ReviewerID,
			&i.Action,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRequests = `-- name: ListApprovalRequests :many

SELECT id, project_id, episode_id, type, submitter_id, resource_id, resource_type, status, workflow_id, run_id, created_at, updated_at
FROM approval_requests
WHERE project_id = $1
  AND ($2::uuid IS NULL OR episode_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::text IS NULL OR type = $4)
ORDER BY created_at DESC
`

type ListApprovalRequestsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   pgtype.UUID `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
}

// Approval Requests
func (q *Queries) ListApprovalRequests(ctx context.Context, arg ListApprovalRequestsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listApprovalRequests,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EpisodeID,
			&i.Type,
			&i.SubmitterID,
			&i.ResourceID,
			&i.ResourceType,
			&i.Status,
			&i.WorkflowID,
			&i.RunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeProductions = `-- name: ListEpisodeProductions :many

SELECT id, project_id, episode_id, status, deadline, progress_percent, workflow_id, run_id, created_at, updated_at
FROM episode_productions
WHERE project_id = $1
ORDER BY created_at ASC
`

// Episode Productions
func (q *Queries) ListEpisodeProductions(ctx context.Context, projectID pgtype.UUID) ([]EpisodeProduction, error) {
	rows, err := q.db.Query(ctx, listEpisodeProductions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeProduction
	for rows.Next() {
		var i EpisodeProduction
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EpisodeID,
			&i.Status,
			&i.Deadline,
			&i.ProgressPercent,
			&i.WorkflowID,
			&i.RunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many

SELECT id, project_id, episode_id, title, description, assignee_id, role_id, status, deadline, workflow_id, run_id, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND ($2::uuid IS NULL OR episode_id = $2)
  AND ($3::uuid IS NULL OR assignee_id = $3)
  AND ($4::text IS NULL OR status = $4)
ORDER BY created_at DESC
`

type ListTasksParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   pgtype.UUID `json:"column_2"`
	Column3   pgtype.UUID `json:"column_3"`
	Column4   string      `json:"column_4"`
}

// Tasks
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EpisodeID,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.RoleID,
			&i.Status,
			&i.Deadline,
			&i.WorkflowID,
			&i.RunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalRequestStatus = `-- name: UpdateApprovalRequestStatus :one
UPDATE approval_requests
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, episode_id, type, submitter_id, resource_id, resource_type, status, workflow_id, run_id, created_at, updated_at
`

type UpdateApprovalRequestStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateApprovalRequestStatus(ctx context.Context, arg UpdateApprovalRequestStatusParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, updateApprovalRequestStatus, arg.ID, arg.Status)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Type,
		&i.SubmitterID,
		&i.ResourceID,
		&i.ResourceType,
		&i.Status,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApprovalRequestWorkflow = `-- name: UpdateApprovalRequestWorkflow :one
UPDATE approval_requests
SET workflow_id = $2, run_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, episode_id, type, submitter_id, resource_id, resource_type, status, workflow_id, run_id, created_at, updated_at
`

type UpdateApprovalRequestWorkflowParams struct {
	ID         pgtype.UUID `json:"id"`
	WorkflowID pgtype.Text `json:"workflow_id"`
	RunID      pgtype.Text `json:"run_id"`
}

func (q *Queries) UpdateApprovalRequestWorkflow(ctx context.Context, arg UpdateApprovalRequestWorkflowParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, updateApprovalRequestWorkflow, arg.ID, arg.WorkflowID, arg.RunID)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Type,
		&i.SubmitterID,
		&i.ResourceID,
		&i.ResourceType,
		&i.Status,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEpisodeProductionStatus = `-- name: UpdateEpisodeProductionStatus :one
UPDATE episode_productions
SET status = $3, progress_percent = COALESCE($4, progress_percent), updated_at = NOW()
WHERE project_id = $1 AND episode_id = $2
RETURNING id, project_id, episode_id, status, deadline, progress_percent, workflow_id, run_id, created_at, updated_at
`

type UpdateEpisodeProductionStatusParams struct {
	ProjectID       pgtype.UUID    `json:"project_id"`
	EpisodeID       pgtype.UUID    `json:"episode_id"`
	Status          string         `json:"status"`
	ProgressPercent pgtype.Numeric `json:"progress_percent"`
}

func (q *Queries) UpdateEpisodeProductionStatus(ctx context.Context, arg UpdateEpisodeProductionStatusParams) (EpisodeProduction, error) {
	row := q.db.QueryRow(ctx, updateEpisodeProductionStatus,
		arg.ProjectID,
		arg.EpisodeID,
		arg.Status,
		arg.ProgressPercent,
	)
	var i EpisodeProduction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Status,
		&i.Deadline,
		&i.ProgressPercent,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEpisodeProductionWorkflow = `-- name: UpdateEpisodeProductionWorkflow :one
UPDATE episode_productions
SET workflow_id = $3, run_id = $4, updated_at = NOW()
WHERE project_id = $1 AND episode_id = $2
RETURNING id, project_id, episode_id, status, deadline, progress_percent, workflow_id, run_id, created_at, updated_at
`

type UpdateEpisodeProductionWorkflowParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EpisodeID  pgtype.UUID `json:"episode_id"`
	WorkflowID pgtype.Text `json:"workflow_id"`
	RunID      pgtype.Text `json:"run_id"`
}

func (q *Queries) UpdateEpisodeProductionWorkflow(ctx context.Context, arg UpdateEpisodeProductionWorkflowParams) (EpisodeProduction, error) {
	row := q.db.QueryRow(ctx, updateEpisodeProductionWorkflow,
		arg.ProjectID,
		arg.EpisodeID,
		arg.WorkflowID,
		arg.RunID,
	)
	var i EpisodeProduction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Status,
		&i.Deadline,
		&i.ProgressPercent,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskAssignee = `-- name: UpdateTaskAssignee :one
UPDATE tasks
SET assignee_id = $2, status = CASE WHEN status = 'created' THEN 'assigned' ELSE status END, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, episode_id, title, description, assignee_id, role_id, status, deadline, workflow_id, run_id, created_at, updated_at
`

type UpdateTaskAssigneeParams struct {
	ID         pgtype.UUID `json:"id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

func (q *Queries) UpdateTaskAssignee(ctx context.Context, arg UpdateTaskAssigneeParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskAssignee, arg.ID, arg.AssigneeID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.RoleID,
		&i.Status,
		&i.Deadline,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, episode_id, title, description, assignee_id, role_id, status, deadline, workflow_id, run_id, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.RoleID,
		&i.Status,
		&i.Deadline,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskWorkflow = `-- name: UpdateTaskWorkflow :one
UPDATE tasks
SET workflow_id = $2, run_id = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, episode_id, title, description, assignee_id, role_id, status, deadline, workflow_id, run_id, created_at, updated_at
`

type UpdateTaskWorkflowParams struct {
	ID         pgtype.UUID `json:"id"`
	WorkflowID pgtype.Text `json:"workflow_id"`
	RunID      pgtype.Text `json:"run_id"`
}

func (q *Queries) UpdateTaskWorkflow(ctx context.Context, arg UpdateTaskWorkflowParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskWorkflow, arg.ID, arg.WorkflowID, arg.RunID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.RoleID,
		&i.Status,
		&i.Deadline,
		&i.WorkflowID,
		&i.RunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
