apiVersion: v1
kind: Service
metadata:
  name: storyboard-frontend
  namespace: storyboard-editor
  labels:
    app: storyboard-frontend
spec:
  type: ClusterIP
  ports:
    - port: 1421
      targetPort: 1421
      protocol: TCP
      name: http
  selector:
    app: storyboard-frontend
