import type { DataSource } from '$houdini/runtime'

export type Result<DataType> = {
	isFetching: boolean
	partial: boolean
	source?: DataSource | null
	data?: DataType | null
	error?: Error | null
}
export * from './CreateAudioClip'
export * from './CreateAudioTrack'
export * from './CreateCharacter'
export * from './CreateComposer'
export * from './CreateDialogue'
export * from './CreateEpisode'
export * from './CreatePart'
export * from './CreateProject'
export * from './CreateScenario'
export * from './CreateScene'
export * from './CreateScenePlan'
export * from './CreateStoryboard'
export * from './DeleteAudioClip'
export * from './DeleteCharacter'
export * from './DeleteCharacterAsset'
export * from './DeleteDialogue'
export * from './DeleteScenario'
export * from './DeleteScene'
export * from './GenerateDialogueAudio'
export * from './GenerateSceneImage'
export * from './GenerateSunoMusic'
export * from './GenerateVideo'
export * from './GetCharacterAssetData'
export * from './GetComposer'
export * from './GetGeneratedImages'
export * from './GetScenario'
export * from './GetScene'
export * from './ListAudioClips'
export * from './ListAudioTracks'
export * from './ListCharacterAssets'
export * from './ListCharacters'
export * from './ListComposers'
export * from './ListDialogues'
export * from './ListGeneratedVideos'
export * from './ListHumeVoices'
export * from './ListProjects'
export * from './ListScenarios'
export * from './ListScenes'
export * from './ListStoryboards'
export * from './ListSunoMusic'
export * from './ReorderAudioClips'
export * from './ReorderScenes'
export * from './TranslateDialogue'
export * from './UpdateAudioClip'
export * from './UpdateCharacter'
export * from './UpdateDialogue'
export * from './UpdateScenario'
export * from './UpdateScene'
export * from './UploadCharacterAsset'
export * from './UploadSceneImage'