// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generated_videos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGeneratedVideo = `-- name: CreateGeneratedVideo :one
INSERT INTO generated_videos (storyboard_id, variation_number, status, org_id)
VALUES ($1, $2, $3, $4)
RETURNING id, storyboard_id, variation_number, video_url, status, error_message, created_at
`

type CreateGeneratedVideoParams struct {
	StoryboardID    pgtype.UUID `json:"storyboard_id"`
	VariationNumber pgtype.Int4 `json:"variation_number"`
	Status          string      `json:"status"`
	OrgID           pgtype.Text `json:"org_id"`
}

type CreateGeneratedVideoRow struct {
	ID              pgtype.UUID        `json:"id"`
	StoryboardID    pgtype.UUID        `json:"storyboard_id"`
	VariationNumber pgtype.Int4        `json:"variation_number"`
	VideoUrl        pgtype.Text        `json:"video_url"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGeneratedVideo(ctx context.Context, arg CreateGeneratedVideoParams) (CreateGeneratedVideoRow, error) {
	row := q.db.QueryRow(ctx, createGeneratedVideo,
		arg.StoryboardID,
		arg.VariationNumber,
		arg.Status,
		arg.OrgID,
	)
	var i CreateGeneratedVideoRow
	err := row.Scan(
		&i.ID,
		&i.StoryboardID,
		&i.VariationNumber,
		&i.VideoUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGeneratedVideo = `-- name: DeleteGeneratedVideo :exec
DELETE FROM generated_videos WHERE id = $1
`

func (q *Queries) DeleteGeneratedVideo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGeneratedVideo, id)
	return err
}

const getGeneratedVideo = `-- name: GetGeneratedVideo :one
SELECT id, storyboard_id, variation_number, video_url, status, error_message, created_at
FROM generated_videos
WHERE id = $1
`

type GetGeneratedVideoRow struct {
	ID              pgtype.UUID        `json:"id"`
	StoryboardID    pgtype.UUID        `json:"storyboard_id"`
	VariationNumber pgtype.Int4        `json:"variation_number"`
	VideoUrl        pgtype.Text        `json:"video_url"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGeneratedVideo(ctx context.Context, id pgtype.UUID) (GetGeneratedVideoRow, error) {
	row := q.db.QueryRow(ctx, getGeneratedVideo, id)
	var i GetGeneratedVideoRow
	err := row.Scan(
		&i.ID,
		&i.StoryboardID,
		&i.VariationNumber,
		&i.VideoUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listGeneratedVideos = `-- name: ListGeneratedVideos :many
SELECT id, storyboard_id, variation_number, video_url, status, error_message, created_at
FROM generated_videos
WHERE storyboard_id = $1
ORDER BY variation_number ASC, created_at DESC
`

type ListGeneratedVideosRow struct {
	ID              pgtype.UUID        `json:"id"`
	StoryboardID    pgtype.UUID        `json:"storyboard_id"`
	VariationNumber pgtype.Int4        `json:"variation_number"`
	VideoUrl        pgtype.Text        `json:"video_url"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGeneratedVideos(ctx context.Context, storyboardID pgtype.UUID) ([]ListGeneratedVideosRow, error) {
	rows, err := q.db.Query(ctx, listGeneratedVideos, storyboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGeneratedVideosRow
	for rows.Next() {
		var i ListGeneratedVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryboardID,
			&i.VariationNumber,
			&i.VideoUrl,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGeneratedVideoStatus = `-- name: UpdateGeneratedVideoStatus :one
UPDATE generated_videos
SET status = $2,
    video_url = $3,
    error_message = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, storyboard_id, variation_number, video_url, status, error_message, created_at
`

type UpdateGeneratedVideoStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	VideoUrl     pgtype.Text `json:"video_url"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

type UpdateGeneratedVideoStatusRow struct {
	ID              pgtype.UUID        `json:"id"`
	StoryboardID    pgtype.UUID        `json:"storyboard_id"`
	VariationNumber pgtype.Int4        `json:"variation_number"`
	VideoUrl        pgtype.Text        `json:"video_url"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateGeneratedVideoStatus(ctx context.Context, arg UpdateGeneratedVideoStatusParams) (UpdateGeneratedVideoStatusRow, error) {
	row := q.db.QueryRow(ctx, updateGeneratedVideoStatus,
		arg.ID,
		arg.Status,
		arg.VideoUrl,
		arg.ErrorMessage,
	)
	var i UpdateGeneratedVideoStatusRow
	err := row.Scan(
		&i.ID,
		&i.StoryboardID,
		&i.VariationNumber,
		&i.VideoUrl,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}
