// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAudioClip(ctx context.Context, arg CreateAudioClipParams) (AudioClip, error)
	CreateAudioTrack(ctx context.Context, arg CreateAudioTrackParams) (AudioTrack, error)
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (CreateCharacterRow, error)
	CreateCharacterAsset(ctx context.Context, arg CreateCharacterAssetParams) (CreateCharacterAssetRow, error)
	CreateComposer(ctx context.Context, arg CreateComposerParams) (Composer, error)
	CreateDialogue(ctx context.Context, arg CreateDialogueParams) (CreateDialogueRow, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (CreateEpisodeRow, error)
	CreateGeneratedImage(ctx context.Context, arg CreateGeneratedImageParams) (CreateGeneratedImageRow, error)
	CreateGeneratedVideo(ctx context.Context, arg CreateGeneratedVideoParams) (CreateGeneratedVideoRow, error)
	CreateOperationHistory(ctx context.Context, arg CreateOperationHistoryParams) (CreateOperationHistoryRow, error)
	CreatePart(ctx context.Context, arg CreatePartParams) (CreatePartRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateScenario(ctx context.Context, arg CreateScenarioParams) (CreateScenarioRow, error)
	CreateScene(ctx context.Context, arg CreateSceneParams) (CreateSceneRow, error)
	CreateScenePlan(ctx context.Context, arg CreateScenePlanParams) (CreateScenePlanRow, error)
	CreateStoryboard(ctx context.Context, arg CreateStoryboardParams) (CreateStoryboardRow, error)
	CreateSunoMusic(ctx context.Context, arg CreateSunoMusicParams) (SunoMusic, error)
	DeleteAudioClip(ctx context.Context, id pgtype.UUID) error
	DeleteAudioTrack(ctx context.Context, id pgtype.UUID) error
	DeleteCharacter(ctx context.Context, id pgtype.UUID) error
	DeleteCharacterAsset(ctx context.Context, id pgtype.UUID) error
	DeleteComposer(ctx context.Context, id pgtype.UUID) error
	DeleteDialogue(ctx context.Context, id pgtype.UUID) error
	DeleteEpisode(ctx context.Context, id pgtype.UUID) error
	DeleteGeneratedImage(ctx context.Context, id pgtype.UUID) error
	DeleteGeneratedVideo(ctx context.Context, id pgtype.UUID) error
	DeletePart(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteScenario(ctx context.Context, id pgtype.UUID) error
	DeleteScene(ctx context.Context, id pgtype.UUID) error
	DeleteScenePlan(ctx context.Context, id pgtype.UUID) error
	DeleteStoryboard(ctx context.Context, id pgtype.UUID) error
	DeleteSunoMusic(ctx context.Context, id pgtype.UUID) error
	GetAudioClip(ctx context.Context, id pgtype.UUID) (AudioClip, error)
	GetAudioTrack(ctx context.Context, id pgtype.UUID) (AudioTrack, error)
	GetCharacter(ctx context.Context, id pgtype.UUID) (GetCharacterRow, error)
	GetCharacterAssetData(ctx context.Context, id pgtype.UUID) (GetCharacterAssetDataRow, error)
	GetComposer(ctx context.Context, id pgtype.UUID) (Composer, error)
	GetDialogue(ctx context.Context, id pgtype.UUID) (GetDialogueRow, error)
	GetDialogueAudioData(ctx context.Context, id pgtype.UUID) ([]byte, error)
	GetEpisode(ctx context.Context, id pgtype.UUID) (GetEpisodeRow, error)
	GetGeneratedImage(ctx context.Context, id pgtype.UUID) (GetGeneratedImageRow, error)
	GetGeneratedImageData(ctx context.Context, id pgtype.UUID) (GetGeneratedImageDataRow, error)
	GetGeneratedVideo(ctx context.Context, id pgtype.UUID) (GetGeneratedVideoRow, error)
	GetMaxDialogueOrderIndex(ctx context.Context, sceneID pgtype.UUID) (interface{}, error)
	GetMaxSceneNumber(ctx context.Context, storyboardID pgtype.UUID) (interface{}, error)
	GetPart(ctx context.Context, id pgtype.UUID) (GetPartRow, error)
	GetProject(ctx context.Context, id pgtype.UUID) (GetProjectRow, error)
	GetProjectByIdAndOrg(ctx context.Context, arg GetProjectByIdAndOrgParams) (GetProjectByIdAndOrgRow, error)
	GetProjectOrgId(ctx context.Context, id pgtype.UUID) (pgtype.Text, error)
	GetScenario(ctx context.Context, id pgtype.UUID) (GetScenarioRow, error)
	GetScene(ctx context.Context, id pgtype.UUID) (GetSceneRow, error)
	GetScenePlan(ctx context.Context, id pgtype.UUID) (GetScenePlanRow, error)
	GetStoryboard(ctx context.Context, id pgtype.UUID) (GetStoryboardRow, error)
	GetSunoMusic(ctx context.Context, id pgtype.UUID) (SunoMusic, error)
	ListAudioClips(ctx context.Context, trackID pgtype.UUID) ([]AudioClip, error)
	ListAudioTracks(ctx context.Context, composerID pgtype.UUID) ([]AudioTrack, error)
	ListCharacterAssets(ctx context.Context, characterID pgtype.UUID) ([]ListCharacterAssetsRow, error)
	ListCharacters(ctx context.Context, projectID pgtype.UUID) ([]ListCharactersRow, error)
	ListComposers(ctx context.Context, projectID pgtype.UUID) ([]Composer, error)
	ListDialogues(ctx context.Context, sceneID pgtype.UUID) ([]ListDialoguesRow, error)
	ListEpisodes(ctx context.Context, scenarioID pgtype.UUID) ([]ListEpisodesRow, error)
	ListGeneratedImages(ctx context.Context, sceneID pgtype.UUID) ([]ListGeneratedImagesRow, error)
	ListGeneratedVideos(ctx context.Context, storyboardID pgtype.UUID) ([]ListGeneratedVideosRow, error)
	ListOperationHistory(ctx context.Context) ([]ListOperationHistoryRow, error)
	ListOperationHistoryByEntity(ctx context.Context, arg ListOperationHistoryByEntityParams) ([]ListOperationHistoryByEntityRow, error)
	ListOperationHistoryByType(ctx context.Context, entityType string) ([]ListOperationHistoryByTypeRow, error)
	ListParts(ctx context.Context, episodeID pgtype.UUID) ([]ListPartsRow, error)
	ListProjects(ctx context.Context, dollar_1 string) ([]ListProjectsRow, error)
	ListProjectsByOrg(ctx context.Context, orgID pgtype.Text) ([]ListProjectsByOrgRow, error)
	ListScenarios(ctx context.Context, projectID pgtype.UUID) ([]ListScenariosRow, error)
	ListScenePlans(ctx context.Context, partID pgtype.UUID) ([]ListScenePlansRow, error)
	ListScenes(ctx context.Context, storyboardID pgtype.UUID) ([]ListScenesRow, error)
	ListStoryboards(ctx context.Context, projectID pgtype.UUID) ([]ListStoryboardsRow, error)
	ListSunoMusic(ctx context.Context, composerID pgtype.UUID) ([]SunoMusic, error)
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (UpdateCharacterRow, error)
	UpdateComposer(ctx context.Context, arg UpdateComposerParams) (Composer, error)
	UpdateDialogue(ctx context.Context, arg UpdateDialogueParams) (UpdateDialogueRow, error)
	UpdateDialogueAudio(ctx context.Context, arg UpdateDialogueAudioParams) (UpdateDialogueAudioRow, error)
	UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (UpdateEpisodeRow, error)
	UpdateGeneratedVideoStatus(ctx context.Context, arg UpdateGeneratedVideoStatusParams) (UpdateGeneratedVideoStatusRow, error)
	UpdatePart(ctx context.Context, arg UpdatePartParams) (UpdatePartRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (UpdateScenarioRow, error)
	UpdateScene(ctx context.Context, arg UpdateSceneParams) (UpdateSceneRow, error)
	UpdateScenePlan(ctx context.Context, arg UpdateScenePlanParams) (UpdateScenePlanRow, error)
	UpdateStoryboard(ctx context.Context, arg UpdateStoryboardParams) (UpdateStoryboardRow, error)
	UpdateSunoMusicStatus(ctx context.Context, arg UpdateSunoMusicStatusParams) (SunoMusic, error)
}

var _ Querier = (*Queries)(nil)
