// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: editor.proto

package editorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveStoryboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Scenes        []*StoryboardScene     `protobuf:"bytes,2,rep,name=scenes,proto3" json:"scenes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStoryboardRequest) Reset() {
	*x = SaveStoryboardRequest{}
	mi := &file_editor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStoryboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStoryboardRequest) ProtoMessage() {}

func (x *SaveStoryboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStoryboardRequest.ProtoReflect.Descriptor instead.
func (*SaveStoryboardRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{0}
}

func (x *SaveStoryboardRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SaveStoryboardRequest) GetScenes() []*StoryboardScene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

type SaveStoryboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStoryboardResponse) Reset() {
	*x = SaveStoryboardResponse{}
	mi := &file_editor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStoryboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStoryboardResponse) ProtoMessage() {}

func (x *SaveStoryboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStoryboardResponse.ProtoReflect.Descriptor instead.
func (*SaveStoryboardResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{1}
}

func (x *SaveStoryboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveStoryboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStoryboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryboardRequest) Reset() {
	*x = GetStoryboardRequest{}
	mi := &file_editor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryboardRequest) ProtoMessage() {}

func (x *GetStoryboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryboardRequest.ProtoReflect.Descriptor instead.
func (*GetStoryboardRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{2}
}

func (x *GetStoryboardRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetStoryboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenes        []*StoryboardScene     `protobuf:"bytes,1,rep,name=scenes,proto3" json:"scenes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryboardResponse) Reset() {
	*x = GetStoryboardResponse{}
	mi := &file_editor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryboardResponse) ProtoMessage() {}

func (x *GetStoryboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryboardResponse.ProtoReflect.Descriptor instead.
func (*GetStoryboardResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoryboardResponse) GetScenes() []*StoryboardScene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

type StoryboardScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Visual        string                 `protobuf:"bytes,2,opt,name=visual,proto3" json:"visual,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Audio         string                 `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	Timing        string                 `protobuf:"bytes,5,opt,name=timing,proto3" json:"timing,omitempty"`
	Fps           int32                  `protobuf:"varint,6,opt,name=fps,proto3" json:"fps,omitempty"`
	Persons       []string               `protobuf:"bytes,7,rep,name=persons,proto3" json:"persons,omitempty"`
	Places        []string               `protobuf:"bytes,8,rep,name=places,proto3" json:"places,omitempty"`
	Items         []string               `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	Emotions      []string               `protobuf:"bytes,10,rep,name=emotions,proto3" json:"emotions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryboardScene) Reset() {
	*x = StoryboardScene{}
	mi := &file_editor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryboardScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryboardScene) ProtoMessage() {}

func (x *StoryboardScene) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryboardScene.ProtoReflect.Descriptor instead.
func (*StoryboardScene) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{4}
}

func (x *StoryboardScene) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoryboardScene) GetVisual() string {
	if x != nil {
		return x.Visual
	}
	return ""
}

func (x *StoryboardScene) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StoryboardScene) GetAudio() string {
	if x != nil {
		return x.Audio
	}
	return ""
}

func (x *StoryboardScene) GetTiming() string {
	if x != nil {
		return x.Timing
	}
	return ""
}

func (x *StoryboardScene) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *StoryboardScene) GetPersons() []string {
	if x != nil {
		return x.Persons
	}
	return nil
}

func (x *StoryboardScene) GetPlaces() []string {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *StoryboardScene) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StoryboardScene) GetEmotions() []string {
	if x != nil {
		return x.Emotions
	}
	return nil
}

type InteractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeIds       []string               `protobuf:"bytes,2,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // Participating nodes (Characters, Environment, etc.)
	UserMessage   string                 `protobuf:"bytes,3,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	EmotionBias   map[string]float32     `protobuf:"bytes,4,rep,name=emotion_bias,json=emotionBias,proto3" json:"emotion_bias,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // Optional manual override or base bias
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRequest) Reset() {
	*x = InteractRequest{}
	mi := &file_editor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRequest) ProtoMessage() {}

func (x *InteractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRequest.ProtoReflect.Descriptor instead.
func (*InteractRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{5}
}

func (x *InteractRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InteractRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *InteractRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *InteractRequest) GetEmotionBias() map[string]float32 {
	if x != nil {
		return x.EmotionBias
	}
	return nil
}

type InteractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Which node is responding
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EmotionVector map[string]float32     `protobuf:"bytes,4,rep,name=emotion_vector,json=emotionVector,proto3" json:"emotion_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // Current emotional state of the responding node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractResponse) Reset() {
	*x = InteractResponse{}
	mi := &file_editor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractResponse) ProtoMessage() {}

func (x *InteractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractResponse.ProtoReflect.Descriptor instead.
func (*InteractResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{6}
}

func (x *InteractResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InteractResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *InteractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InteractResponse) GetEmotionVector() map[string]float32 {
	if x != nil {
		return x.EmotionVector
	}
	return nil
}

type CallToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // JSON string of arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_editor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{7}
}

func (x *CallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type CallToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON string of result
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_editor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{8}
}

func (x *CallToolResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type GetProjectMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectMetadataRequest) Reset() {
	*x = GetProjectMetadataRequest{}
	mi := &file_editor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectMetadataRequest) ProtoMessage() {}

func (x *GetProjectMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetProjectMetadataRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{9}
}

func (x *GetProjectMetadataRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Episodes      []*Episode             `protobuf:"bytes,3,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectMetadataResponse) Reset() {
	*x = GetProjectMetadataResponse{}
	mi := &file_editor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectMetadataResponse) ProtoMessage() {}

func (x *GetProjectMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetProjectMetadataResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{10}
}

func (x *GetProjectMetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetProjectMetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProjectMetadataResponse) GetEpisodes() []*Episode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Files         []string               `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_editor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{11}
}

func (x *Episode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Episode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Episode) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type OpenFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileRequest) Reset() {
	*x = OpenFileRequest{}
	mi := &file_editor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRequest) ProtoMessage() {}

func (x *OpenFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRequest.ProtoReflect.Descriptor instead.
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{12}
}

func (x *OpenFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileResponse) Reset() {
	*x = OpenFileResponse{}
	mi := &file_editor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileResponse) ProtoMessage() {}

func (x *OpenFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileResponse.ProtoReflect.Descriptor instead.
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{13}
}

func (x *OpenFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileRequest) Reset() {
	*x = SaveFileRequest{}
	mi := &file_editor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileRequest) ProtoMessage() {}

func (x *SaveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileRequest.ProtoReflect.Descriptor instead.
func (*SaveFileRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{14}
}

func (x *SaveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SaveFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileResponse) Reset() {
	*x = SaveFileResponse{}
	mi := &file_editor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileResponse) ProtoMessage() {}

func (x *SaveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileResponse.ProtoReflect.Descriptor instead.
func (*SaveFileResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{15}
}

func (x *SaveFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AnalyzeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTextRequest) Reset() {
	*x = AnalyzeTextRequest{}
	mi := &file_editor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTextRequest) ProtoMessage() {}

func (x *AnalyzeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTextRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeTextRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{16}
}

func (x *AnalyzeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzeTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTextResponse) Reset() {
	*x = AnalyzeTextResponse{}
	mi := &file_editor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTextResponse) ProtoMessage() {}

func (x *AnalyzeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTextResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeTextResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{17}
}

func (x *AnalyzeTextResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeTextResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_editor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{18}
}

func (x *GetTopologyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_editor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{19}
}

func (x *GetTopologyResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetTopologyResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_editor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{20}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`                  // "entity", "content", "concept", "link-node"
	Embedding     []float32              `protobuf:"fixed32,8,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // LLM-like vector for distance-based layout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_editor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{21}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Node) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Node) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Node) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Node) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Style         string                 `protobuf:"bytes,5,opt,name=style,proto3" json:"style,omitempty"`
	Strength      float32                `protobuf:"fixed32,6,opt,name=strength,proto3" json:"strength,omitempty"` // 0.0 - 1.0
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`         // "structural", "semantic", "causal", "thematic"
	Distance      float32                `protobuf:"fixed32,8,opt,name=distance,proto3" json:"distance,omitempty"` // Preferred distance based on vector similarity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_editor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_editor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_editor_proto_rawDescGZIP(), []int{22}
}

func (x *Edge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Edge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Edge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Edge) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Edge) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *Edge) GetStrength() float32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Edge) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Edge) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_editor_proto protoreflect.FileDescriptor

const file_editor_proto_rawDesc = "" +
	"\n" +
	"\feditor.proto\x12\x1dgftd.ghosthacker.zeneditor.v1\"~\n" +
	"\x15SaveStoryboardRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12F\n" +
	"\x06scenes\x18\x02 \x03(\v2..gftd.ghosthacker.zeneditor.v1.StoryboardSceneR\x06scenes\"L\n" +
	"\x16SaveStoryboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x14GetStoryboardRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"_\n" +
	"\x15GetStoryboardResponse\x12F\n" +
	"\x06scenes\x18\x01 \x03(\v2..gftd.ghosthacker.zeneditor.v1.StoryboardSceneR\x06scenes\"\xff\x01\n" +
	"\x0fStoryboardScene\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06visual\x18\x02 \x01(\tR\x06visual\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05audio\x18\x04 \x01(\tR\x05audio\x12\x16\n" +
	"\x06timing\x18\x05 \x01(\tR\x06timing\x12\x10\n" +
	"\x03fps\x18\x06 \x01(\x05R\x03fps\x12\x18\n" +
	"\apersons\x18\a \x03(\tR\apersons\x12\x16\n" +
	"\x06places\x18\b \x03(\tR\x06places\x12\x14\n" +
	"\x05items\x18\t \x03(\tR\x05items\x12\x1a\n" +
	"\bemotions\x18\n" +
	" \x03(\tR\bemotions\"\x92\x02\n" +
	"\x0fInteractRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bnode_ids\x18\x02 \x03(\tR\anodeIds\x12!\n" +
	"\fuser_message\x18\x03 \x01(\tR\vuserMessage\x12b\n" +
	"\femotion_bias\x18\x04 \x03(\v2?.gftd.ghosthacker.zeneditor.v1.InteractRequest.EmotionBiasEntryR\vemotionBias\x1a>\n" +
	"\x10EmotionBiasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x8f\x02\n" +
	"\x10InteractResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12i\n" +
	"\x0eemotion_vector\x18\x04 \x03(\v2B.gftd.ghosthacker.zeneditor.v1.InteractResponse.EmotionVectorEntryR\remotionVector\x1a@\n" +
	"\x12EmotionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"L\n" +
	"\x0fCallToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\"N\n" +
	"\x10CallToolResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\":\n" +
	"\x19GetProjectMetadataRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x98\x01\n" +
	"\x1aGetProjectMetadataResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12B\n" +
	"\bepisodes\x18\x03 \x03(\v2&.gftd.ghosthacker.zeneditor.v1.EpisodeR\bepisodes\"E\n" +
	"\aEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\"%\n" +
	"\x0fOpenFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10OpenFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"?\n" +
	"\x0fSaveFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\",\n" +
	"\x10SaveFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x12AnalyzeTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"r\n" +
	"\x13AnalyzeTextResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12A\n" +
	"\bentities\x18\x02 \x03(\v2%.gftd.ghosthacker.zeneditor.v1.EntityR\bentities\"3\n" +
	"\x12GetTopologyRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x8b\x01\n" +
	"\x13GetTopologyResponse\x129\n" +
	"\x05nodes\x18\x01 \x03(\v2#.gftd.ghosthacker.zeneditor.v1.NodeR\x05nodes\x129\n" +
	"\x05edges\x18\x02 \x03(\v2#.gftd.ghosthacker.zeneditor.v1.EdgeR\x05edges\"@\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xaa\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x1c\n" +
	"\tembedding\x18\b \x03(\x02R\tembedding\"\xca\x01\n" +
	"\x04Edge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x14\n" +
	"\x05style\x18\x05 \x01(\tR\x05style\x12\x1a\n" +
	"\bstrength\x18\x06 \x01(\x02R\bstrength\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x02R\bdistance2\xe8\x05\n" +
	"\rEditorService\x12t\n" +
	"\vGetTopology\x121.gftd.ghosthacker.zeneditor.v1.GetTopologyRequest\x1a2.gftd.ghosthacker.zeneditor.v1.GetTopologyResponse\x12\x89\x01\n" +
	"\x12GetProjectMetadata\x128.gftd.ghosthacker.zeneditor.v1.GetProjectMetadataRequest\x1a9.gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse\x12k\n" +
	"\bCallTool\x12..gftd.ghosthacker.zeneditor.v1.CallToolRequest\x1a/.gftd.ghosthacker.zeneditor.v1.CallToolResponse\x12}\n" +
	"\x0eSaveStoryboard\x124.gftd.ghosthacker.zeneditor.v1.SaveStoryboardRequest\x1a5.gftd.ghosthacker.zeneditor.v1.SaveStoryboardResponse\x12z\n" +
	"\rGetStoryboard\x123.gftd.ghosthacker.zeneditor.v1.GetStoryboardRequest\x1a4.gftd.ghosthacker.zeneditor.v1.GetStoryboardResponse\x12m\n" +
	"\bInteract\x12..gftd.ghosthacker.zeneditor.v1.InteractRequest\x1a/.gftd.ghosthacker.zeneditor.v1.InteractResponse0\x01BHZFgithub.com/gftd-ai/ghost-hacker/apps/zen-editor/backend/proto;editorpbb\x06proto3"

var (
	file_editor_proto_rawDescOnce sync.Once
	file_editor_proto_rawDescData []byte
)

func file_editor_proto_rawDescGZIP() []byte {
	file_editor_proto_rawDescOnce.Do(func() {
		file_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editor_proto_rawDesc), len(file_editor_proto_rawDesc)))
	})
	return file_editor_proto_rawDescData
}

var file_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_editor_proto_goTypes = []any{
	(*SaveStoryboardRequest)(nil),      // 0: gftd.ghosthacker.zeneditor.v1.SaveStoryboardRequest
	(*SaveStoryboardResponse)(nil),     // 1: gftd.ghosthacker.zeneditor.v1.SaveStoryboardResponse
	(*GetStoryboardRequest)(nil),       // 2: gftd.ghosthacker.zeneditor.v1.GetStoryboardRequest
	(*GetStoryboardResponse)(nil),      // 3: gftd.ghosthacker.zeneditor.v1.GetStoryboardResponse
	(*StoryboardScene)(nil),            // 4: gftd.ghosthacker.zeneditor.v1.StoryboardScene
	(*InteractRequest)(nil),            // 5: gftd.ghosthacker.zeneditor.v1.InteractRequest
	(*InteractResponse)(nil),           // 6: gftd.ghosthacker.zeneditor.v1.InteractResponse
	(*CallToolRequest)(nil),            // 7: gftd.ghosthacker.zeneditor.v1.CallToolRequest
	(*CallToolResponse)(nil),           // 8: gftd.ghosthacker.zeneditor.v1.CallToolResponse
	(*GetProjectMetadataRequest)(nil),  // 9: gftd.ghosthacker.zeneditor.v1.GetProjectMetadataRequest
	(*GetProjectMetadataResponse)(nil), // 10: gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse
	(*Episode)(nil),                    // 11: gftd.ghosthacker.zeneditor.v1.Episode
	(*OpenFileRequest)(nil),            // 12: gftd.ghosthacker.zeneditor.v1.OpenFileRequest
	(*OpenFileResponse)(nil),           // 13: gftd.ghosthacker.zeneditor.v1.OpenFileResponse
	(*SaveFileRequest)(nil),            // 14: gftd.ghosthacker.zeneditor.v1.SaveFileRequest
	(*SaveFileResponse)(nil),           // 15: gftd.ghosthacker.zeneditor.v1.SaveFileResponse
	(*AnalyzeTextRequest)(nil),         // 16: gftd.ghosthacker.zeneditor.v1.AnalyzeTextRequest
	(*AnalyzeTextResponse)(nil),        // 17: gftd.ghosthacker.zeneditor.v1.AnalyzeTextResponse
	(*GetTopologyRequest)(nil),         // 18: gftd.ghosthacker.zeneditor.v1.GetTopologyRequest
	(*GetTopologyResponse)(nil),        // 19: gftd.ghosthacker.zeneditor.v1.GetTopologyResponse
	(*Entity)(nil),                     // 20: gftd.ghosthacker.zeneditor.v1.Entity
	(*Node)(nil),                       // 21: gftd.ghosthacker.zeneditor.v1.Node
	(*Edge)(nil),                       // 22: gftd.ghosthacker.zeneditor.v1.Edge
	nil,                                // 23: gftd.ghosthacker.zeneditor.v1.InteractRequest.EmotionBiasEntry
	nil,                                // 24: gftd.ghosthacker.zeneditor.v1.InteractResponse.EmotionVectorEntry
}
var file_editor_proto_depIdxs = []int32{
	4,  // 0: gftd.ghosthacker.zeneditor.v1.SaveStoryboardRequest.scenes:type_name -> gftd.ghosthacker.zeneditor.v1.StoryboardScene
	4,  // 1: gftd.ghosthacker.zeneditor.v1.GetStoryboardResponse.scenes:type_name -> gftd.ghosthacker.zeneditor.v1.StoryboardScene
	23, // 2: gftd.ghosthacker.zeneditor.v1.InteractRequest.emotion_bias:type_name -> gftd.ghosthacker.zeneditor.v1.InteractRequest.EmotionBiasEntry
	24, // 3: gftd.ghosthacker.zeneditor.v1.InteractResponse.emotion_vector:type_name -> gftd.ghosthacker.zeneditor.v1.InteractResponse.EmotionVectorEntry
	11, // 4: gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse.episodes:type_name -> gftd.ghosthacker.zeneditor.v1.Episode
	20, // 5: gftd.ghosthacker.zeneditor.v1.AnalyzeTextResponse.entities:type_name -> gftd.ghosthacker.zeneditor.v1.Entity
	21, // 6: gftd.ghosthacker.zeneditor.v1.GetTopologyResponse.nodes:type_name -> gftd.ghosthacker.zeneditor.v1.Node
	22, // 7: gftd.ghosthacker.zeneditor.v1.GetTopologyResponse.edges:type_name -> gftd.ghosthacker.zeneditor.v1.Edge
	18, // 8: gftd.ghosthacker.zeneditor.v1.EditorService.GetTopology:input_type -> gftd.ghosthacker.zeneditor.v1.GetTopologyRequest
	9,  // 9: gftd.ghosthacker.zeneditor.v1.EditorService.GetProjectMetadata:input_type -> gftd.ghosthacker.zeneditor.v1.GetProjectMetadataRequest
	7,  // 10: gftd.ghosthacker.zeneditor.v1.EditorService.CallTool:input_type -> gftd.ghosthacker.zeneditor.v1.CallToolRequest
	0,  // 11: gftd.ghosthacker.zeneditor.v1.EditorService.SaveStoryboard:input_type -> gftd.ghosthacker.zeneditor.v1.SaveStoryboardRequest
	2,  // 12: gftd.ghosthacker.zeneditor.v1.EditorService.GetStoryboard:input_type -> gftd.ghosthacker.zeneditor.v1.GetStoryboardRequest
	5,  // 13: gftd.ghosthacker.zeneditor.v1.EditorService.Interact:input_type -> gftd.ghosthacker.zeneditor.v1.InteractRequest
	19, // 14: gftd.ghosthacker.zeneditor.v1.EditorService.GetTopology:output_type -> gftd.ghosthacker.zeneditor.v1.GetTopologyResponse
	10, // 15: gftd.ghosthacker.zeneditor.v1.EditorService.GetProjectMetadata:output_type -> gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse
	8,  // 16: gftd.ghosthacker.zeneditor.v1.EditorService.CallTool:output_type -> gftd.ghosthacker.zeneditor.v1.CallToolResponse
	1,  // 17: gftd.ghosthacker.zeneditor.v1.EditorService.SaveStoryboard:output_type -> gftd.ghosthacker.zeneditor.v1.SaveStoryboardResponse
	3,  // 18: gftd.ghosthacker.zeneditor.v1.EditorService.GetStoryboard:output_type -> gftd.ghosthacker.zeneditor.v1.GetStoryboardResponse
	6,  // 19: gftd.ghosthacker.zeneditor.v1.EditorService.Interact:output_type -> gftd.ghosthacker.zeneditor.v1.InteractResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_editor_proto_init() }
func file_editor_proto_init() {
	if File_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editor_proto_rawDesc), len(file_editor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_editor_proto_goTypes,
		DependencyIndexes: file_editor_proto_depIdxs,
		MessageInfos:      file_editor_proto_msgTypes,
	}.Build()
	File_editor_proto = out.File
	file_editor_proto_goTypes = nil
	file_editor_proto_depIdxs = nil
}
