// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/editor.proto

package editorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"` // JSON string of arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_editor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{0}
}

func (x *CallToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type CallToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON string of result
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_proto_editor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{1}
}

func (x *CallToolResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type GetProjectMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectMetadataRequest) Reset() {
	*x = GetProjectMetadataRequest{}
	mi := &file_proto_editor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectMetadataRequest) ProtoMessage() {}

func (x *GetProjectMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetProjectMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectMetadataRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Episodes      []*Episode             `protobuf:"bytes,3,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectMetadataResponse) Reset() {
	*x = GetProjectMetadataResponse{}
	mi := &file_proto_editor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectMetadataResponse) ProtoMessage() {}

func (x *GetProjectMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetProjectMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectMetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetProjectMetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProjectMetadataResponse) GetEpisodes() []*Episode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Files         []string               `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_proto_editor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{4}
}

func (x *Episode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Episode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Episode) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type OpenFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileRequest) Reset() {
	*x = OpenFileRequest{}
	mi := &file_proto_editor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRequest) ProtoMessage() {}

func (x *OpenFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRequest.ProtoReflect.Descriptor instead.
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{5}
}

func (x *OpenFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileResponse) Reset() {
	*x = OpenFileResponse{}
	mi := &file_proto_editor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileResponse) ProtoMessage() {}

func (x *OpenFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileResponse.ProtoReflect.Descriptor instead.
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{6}
}

func (x *OpenFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileRequest) Reset() {
	*x = SaveFileRequest{}
	mi := &file_proto_editor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileRequest) ProtoMessage() {}

func (x *SaveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileRequest.ProtoReflect.Descriptor instead.
func (*SaveFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{7}
}

func (x *SaveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SaveFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileResponse) Reset() {
	*x = SaveFileResponse{}
	mi := &file_proto_editor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileResponse) ProtoMessage() {}

func (x *SaveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileResponse.ProtoReflect.Descriptor instead.
func (*SaveFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{8}
}

func (x *SaveFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AnalyzeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTextRequest) Reset() {
	*x = AnalyzeTextRequest{}
	mi := &file_proto_editor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTextRequest) ProtoMessage() {}

func (x *AnalyzeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTextRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{9}
}

func (x *AnalyzeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AnalyzeTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTextResponse) Reset() {
	*x = AnalyzeTextResponse{}
	mi := &file_proto_editor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTextResponse) ProtoMessage() {}

func (x *AnalyzeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTextResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeTextResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeTextResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetTopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_proto_editor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{11}
}

func (x *GetTopologyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_proto_editor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{12}
}

func (x *GetTopologyResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetTopologyResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_proto_editor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{13}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_editor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{14}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Node) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_proto_editor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_proto_editor_proto_rawDescGZIP(), []int{15}
}

func (x *Edge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Edge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Edge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

var File_proto_editor_proto protoreflect.FileDescriptor

const file_proto_editor_proto_rawDesc = "" +
	"\n" +
	"\x12proto/editor.proto\x12\x1dgftd.ghosthacker.zeneditor.v1\"L\n" +
	"\x0fCallToolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\"N\n" +
	"\x10CallToolResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\":\n" +
	"\x19GetProjectMetadataRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x98\x01\n" +
	"\x1aGetProjectMetadataResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12B\n" +
	"\bepisodes\x18\x03 \x03(\v2&.gftd.ghosthacker.zeneditor.v1.EpisodeR\bepisodes\"E\n" +
	"\aEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\"%\n" +
	"\x0fOpenFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10OpenFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"?\n" +
	"\x0fSaveFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\",\n" +
	"\x10SaveFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x12AnalyzeTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"r\n" +
	"\x13AnalyzeTextResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12A\n" +
	"\bentities\x18\x02 \x03(\v2%.gftd.ghosthacker.zeneditor.v1.EntityR\bentities\"3\n" +
	"\x12GetTopologyRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x8b\x01\n" +
	"\x13GetTopologyResponse\x129\n" +
	"\x05nodes\x18\x01 \x03(\v2#.gftd.ghosthacker.zeneditor.v1.NodeR\x05nodes\x129\n" +
	"\x05edges\x18\x02 \x03(\v2#.gftd.ghosthacker.zeneditor.v1.EdgeR\x05edges\"@\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\\\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\"P\n" +
	"\x04Edge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation2\xfe\x02\n" +
	"\rEditorService\x12t\n" +
	"\vGetTopology\x121.gftd.ghosthacker.zeneditor.v1.GetTopologyRequest\x1a2.gftd.ghosthacker.zeneditor.v1.GetTopologyResponse\x12\x89\x01\n" +
	"\x12GetProjectMetadata\x128.gftd.ghosthacker.zeneditor.v1.GetProjectMetadataRequest\x1a9.gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse\x12k\n" +
	"\bCallTool\x12..gftd.ghosthacker.zeneditor.v1.CallToolRequest\x1a/.gftd.ghosthacker.zeneditor.v1.CallToolResponseBHZFgithub.com/gftd-ai/ghost-hacker/apps/zen-editor/backend/proto;editorpbb\x06proto3"

var (
	file_proto_editor_proto_rawDescOnce sync.Once
	file_proto_editor_proto_rawDescData []byte
)

func file_proto_editor_proto_rawDescGZIP() []byte {
	file_proto_editor_proto_rawDescOnce.Do(func() {
		file_proto_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_editor_proto_rawDesc), len(file_proto_editor_proto_rawDesc)))
	})
	return file_proto_editor_proto_rawDescData
}

var file_proto_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_editor_proto_goTypes = []any{
	(*CallToolRequest)(nil),            // 0: gftd.ghosthacker.zeneditor.v1.CallToolRequest
	(*CallToolResponse)(nil),           // 1: gftd.ghosthacker.zeneditor.v1.CallToolResponse
	(*GetProjectMetadataRequest)(nil),  // 2: gftd.ghosthacker.zeneditor.v1.GetProjectMetadataRequest
	(*GetProjectMetadataResponse)(nil), // 3: gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse
	(*Episode)(nil),                    // 4: gftd.ghosthacker.zeneditor.v1.Episode
	(*OpenFileRequest)(nil),            // 5: gftd.ghosthacker.zeneditor.v1.OpenFileRequest
	(*OpenFileResponse)(nil),           // 6: gftd.ghosthacker.zeneditor.v1.OpenFileResponse
	(*SaveFileRequest)(nil),            // 7: gftd.ghosthacker.zeneditor.v1.SaveFileRequest
	(*SaveFileResponse)(nil),           // 8: gftd.ghosthacker.zeneditor.v1.SaveFileResponse
	(*AnalyzeTextRequest)(nil),         // 9: gftd.ghosthacker.zeneditor.v1.AnalyzeTextRequest
	(*AnalyzeTextResponse)(nil),        // 10: gftd.ghosthacker.zeneditor.v1.AnalyzeTextResponse
	(*GetTopologyRequest)(nil),         // 11: gftd.ghosthacker.zeneditor.v1.GetTopologyRequest
	(*GetTopologyResponse)(nil),        // 12: gftd.ghosthacker.zeneditor.v1.GetTopologyResponse
	(*Entity)(nil),                     // 13: gftd.ghosthacker.zeneditor.v1.Entity
	(*Node)(nil),                       // 14: gftd.ghosthacker.zeneditor.v1.Node
	(*Edge)(nil),                       // 15: gftd.ghosthacker.zeneditor.v1.Edge
}
var file_proto_editor_proto_depIdxs = []int32{
	4,  // 0: gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse.episodes:type_name -> gftd.ghosthacker.zeneditor.v1.Episode
	13, // 1: gftd.ghosthacker.zeneditor.v1.AnalyzeTextResponse.entities:type_name -> gftd.ghosthacker.zeneditor.v1.Entity
	14, // 2: gftd.ghosthacker.zeneditor.v1.GetTopologyResponse.nodes:type_name -> gftd.ghosthacker.zeneditor.v1.Node
	15, // 3: gftd.ghosthacker.zeneditor.v1.GetTopologyResponse.edges:type_name -> gftd.ghosthacker.zeneditor.v1.Edge
	11, // 4: gftd.ghosthacker.zeneditor.v1.EditorService.GetTopology:input_type -> gftd.ghosthacker.zeneditor.v1.GetTopologyRequest
	2,  // 5: gftd.ghosthacker.zeneditor.v1.EditorService.GetProjectMetadata:input_type -> gftd.ghosthacker.zeneditor.v1.GetProjectMetadataRequest
	0,  // 6: gftd.ghosthacker.zeneditor.v1.EditorService.CallTool:input_type -> gftd.ghosthacker.zeneditor.v1.CallToolRequest
	12, // 7: gftd.ghosthacker.zeneditor.v1.EditorService.GetTopology:output_type -> gftd.ghosthacker.zeneditor.v1.GetTopologyResponse
	3,  // 8: gftd.ghosthacker.zeneditor.v1.EditorService.GetProjectMetadata:output_type -> gftd.ghosthacker.zeneditor.v1.GetProjectMetadataResponse
	1,  // 9: gftd.ghosthacker.zeneditor.v1.EditorService.CallTool:output_type -> gftd.ghosthacker.zeneditor.v1.CallToolResponse
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_editor_proto_init() }
func file_proto_editor_proto_init() {
	if File_proto_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_editor_proto_rawDesc), len(file_proto_editor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_editor_proto_goTypes,
		DependencyIndexes: file_proto_editor_proto_depIdxs,
		MessageInfos:      file_proto_editor_proto_msgTypes,
	}.Build()
	File_proto_editor_proto = out.File
	file_proto_editor_proto_goTypes = nil
	file_proto_editor_proto_depIdxs = nil
}
