// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (project_id, name, description, personality, background, default_hume_voice_id, org_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, description, personality, background, default_hume_voice_id, profile_image_id, created_at, updated_at
`

type CreateCharacterParams struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	Name               string      `json:"name"`
	Description        pgtype.Text `json:"description"`
	Personality        pgtype.Text `json:"personality"`
	Background         pgtype.Text `json:"background"`
	DefaultHumeVoiceID pgtype.Text `json:"default_hume_voice_id"`
	OrgID              pgtype.Text `json:"org_id"`
}

type CreateCharacterRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Personality        pgtype.Text        `json:"personality"`
	Background         pgtype.Text        `json:"background"`
	DefaultHumeVoiceID pgtype.Text        `json:"default_hume_voice_id"`
	ProfileImageID     pgtype.UUID        `json:"profile_image_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (CreateCharacterRow, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Personality,
		arg.Background,
		arg.DefaultHumeVoiceID,
		arg.OrgID,
	)
	var i CreateCharacterRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Background,
		&i.DefaultHumeVoiceID,
		&i.ProfileImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCharacterAsset = `-- name: CreateCharacterAsset :one
INSERT INTO character_assets (character_id, asset_type, asset_data, asset_format, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, character_id, asset_type, asset_format, created_at, updated_at
`

type CreateCharacterAssetParams struct {
	CharacterID pgtype.UUID `json:"character_id"`
	AssetType   string      `json:"asset_type"`
	AssetData   []byte      `json:"asset_data"`
	AssetFormat pgtype.Text `json:"asset_format"`
	OrgID       pgtype.Text `json:"org_id"`
}

type CreateCharacterAssetRow struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	AssetType   string             `json:"asset_type"`
	AssetFormat pgtype.Text        `json:"asset_format"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCharacterAsset(ctx context.Context, arg CreateCharacterAssetParams) (CreateCharacterAssetRow, error) {
	row := q.db.QueryRow(ctx, createCharacterAsset,
		arg.CharacterID,
		arg.AssetType,
		arg.AssetData,
		arg.AssetFormat,
		arg.OrgID,
	)
	var i CreateCharacterAssetRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.AssetType,
		&i.AssetFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const deleteCharacterAsset = `-- name: DeleteCharacterAsset :exec
DELETE FROM character_assets WHERE id = $1
`

func (q *Queries) DeleteCharacterAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacterAsset, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, project_id, name, description, personality, background, default_hume_voice_id, profile_image_id, created_at, updated_at
FROM characters
WHERE id = $1
`

type GetCharacterRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Personality        pgtype.Text        `json:"personality"`
	Background         pgtype.Text        `json:"background"`
	DefaultHumeVoiceID pgtype.Text        `json:"default_hume_voice_id"`
	ProfileImageID     pgtype.UUID        `json:"profile_image_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCharacter(ctx context.Context, id pgtype.UUID) (GetCharacterRow, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i GetCharacterRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Background,
		&i.DefaultHumeVoiceID,
		&i.ProfileImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterAssetData = `-- name: GetCharacterAssetData :one
SELECT asset_data, asset_format FROM character_assets WHERE id = $1
`

type GetCharacterAssetDataRow struct {
	AssetData   []byte      `json:"asset_data"`
	AssetFormat pgtype.Text `json:"asset_format"`
}

func (q *Queries) GetCharacterAssetData(ctx context.Context, id pgtype.UUID) (GetCharacterAssetDataRow, error) {
	row := q.db.QueryRow(ctx, getCharacterAssetData, id)
	var i GetCharacterAssetDataRow
	err := row.Scan(&i.AssetData, &i.AssetFormat)
	return i, err
}

const listCharacterAssets = `-- name: ListCharacterAssets :many
SELECT id, character_id, asset_type, asset_format, created_at, updated_at
FROM character_assets
WHERE character_id = $1
ORDER BY created_at DESC
`

type ListCharacterAssetsRow struct {
	ID          pgtype.UUID        `json:"id"`
	CharacterID pgtype.UUID        `json:"character_id"`
	AssetType   string             `json:"asset_type"`
	AssetFormat pgtype.Text        `json:"asset_format"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCharacterAssets(ctx context.Context, characterID pgtype.UUID) ([]ListCharacterAssetsRow, error) {
	rows, err := q.db.Query(ctx, listCharacterAssets, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterAssetsRow
	for rows.Next() {
		var i ListCharacterAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.AssetType,
			&i.AssetFormat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, project_id, name, description, personality, background, default_hume_voice_id, profile_image_id, created_at, updated_at
FROM characters
WHERE project_id = $1
ORDER BY created_at ASC
`

type ListCharactersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Personality        pgtype.Text        `json:"personality"`
	Background         pgtype.Text        `json:"background"`
	DefaultHumeVoiceID pgtype.Text        `json:"default_hume_voice_id"`
	ProfileImageID     pgtype.UUID        `json:"profile_image_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCharacters(ctx context.Context, projectID pgtype.UUID) ([]ListCharactersRow, error) {
	rows, err := q.db.Query(ctx, listCharacters, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersRow
	for rows.Next() {
		var i ListCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Personality,
			&i.Background,
			&i.DefaultHumeVoiceID,
			&i.ProfileImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    personality = COALESCE($4, personality),
    background = COALESCE($5, background),
    default_hume_voice_id = COALESCE($6, default_hume_voice_id),
    profile_image_id = COALESCE($7, profile_image_id),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, description, personality, background, default_hume_voice_id, profile_image_id, created_at, updated_at
`

type UpdateCharacterParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Description        pgtype.Text `json:"description"`
	Personality        pgtype.Text `json:"personality"`
	Background         pgtype.Text `json:"background"`
	DefaultHumeVoiceID pgtype.Text `json:"default_hume_voice_id"`
	ProfileImageID     pgtype.UUID `json:"profile_image_id"`
}

type UpdateCharacterRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Personality        pgtype.Text        `json:"personality"`
	Background         pgtype.Text        `json:"background"`
	DefaultHumeVoiceID pgtype.Text        `json:"default_hume_voice_id"`
	ProfileImageID     pgtype.UUID        `json:"profile_image_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (UpdateCharacterRow, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Personality,
		arg.Background,
		arg.DefaultHumeVoiceID,
		arg.ProfileImageID,
	)
	var i UpdateCharacterRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Background,
		&i.DefaultHumeVoiceID,
		&i.ProfileImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
