// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: novel_chapters.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNovelChapter = `-- name: CreateNovelChapter :one
INSERT INTO novel_chapters (novel_project_id, title, order_index)
VALUES ($1, $2, $3)
RETURNING id, novel_project_id, title, order_index, content_html, content_json, created_at, updated_at
`

type CreateNovelChapterParams struct {
	NovelProjectID pgtype.UUID `json:"novel_project_id"`
	Title          string      `json:"title"`
	OrderIndex     int32       `json:"order_index"`
}

func (q *Queries) CreateNovelChapter(ctx context.Context, arg CreateNovelChapterParams) (NovelChapter, error) {
	row := q.db.QueryRow(ctx, createNovelChapter, arg.NovelProjectID, arg.Title, arg.OrderIndex)
	var i NovelChapter
	err := row.Scan(
		&i.ID,
		&i.NovelProjectID,
		&i.Title,
		&i.OrderIndex,
		&i.ContentHtml,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNovelChapter = `-- name: DeleteNovelChapter :exec
DELETE FROM novel_chapters WHERE id = $1
`

func (q *Queries) DeleteNovelChapter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNovelChapter, id)
	return err
}

const getNovelChapter = `-- name: GetNovelChapter :one
SELECT id, novel_project_id, title, order_index, content_html, content_json, created_at, updated_at
FROM novel_chapters
WHERE id = $1
`

func (q *Queries) GetNovelChapter(ctx context.Context, id pgtype.UUID) (NovelChapter, error) {
	row := q.db.QueryRow(ctx, getNovelChapter, id)
	var i NovelChapter
	err := row.Scan(
		&i.ID,
		&i.NovelProjectID,
		&i.Title,
		&i.OrderIndex,
		&i.ContentHtml,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNovelChapters = `-- name: ListNovelChapters :many
SELECT id, novel_project_id, title, order_index, content_html, content_json, created_at, updated_at
FROM novel_chapters
WHERE novel_project_id = $1
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListNovelChapters(ctx context.Context, novelProjectID pgtype.UUID) ([]NovelChapter, error) {
	rows, err := q.db.Query(ctx, listNovelChapters, novelProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NovelChapter
	for rows.Next() {
		var i NovelChapter
		if err := rows.Scan(
			&i.ID,
			&i.NovelProjectID,
			&i.Title,
			&i.OrderIndex,
			&i.ContentHtml,
			&i.ContentJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNovelChapter = `-- name: UpdateNovelChapter :one
UPDATE novel_chapters
SET title = COALESCE($2, title),
    order_index = COALESCE($3, order_index),
    updated_at = NOW()
WHERE id = $1
RETURNING id, novel_project_id, title, order_index, content_html, content_json, created_at, updated_at
`

type UpdateNovelChapterParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	OrderIndex int32       `json:"order_index"`
}

func (q *Queries) UpdateNovelChapter(ctx context.Context, arg UpdateNovelChapterParams) (NovelChapter, error) {
	row := q.db.QueryRow(ctx, updateNovelChapter, arg.ID, arg.Title, arg.OrderIndex)
	var i NovelChapter
	err := row.Scan(
		&i.ID,
		&i.NovelProjectID,
		&i.Title,
		&i.OrderIndex,
		&i.ContentHtml,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNovelChapterContent = `-- name: UpdateNovelChapterContent :one
UPDATE novel_chapters
SET content_html = COALESCE($2, content_html),
    content_json = COALESCE($3, content_json),
    updated_at = NOW()
WHERE id = $1
RETURNING id, novel_project_id, title, order_index, content_html, content_json, created_at, updated_at
`

type UpdateNovelChapterContentParams struct {
	ID          pgtype.UUID `json:"id"`
	ContentHtml pgtype.Text `json:"content_html"`
	ContentJson pgtype.Text `json:"content_json"`
}

func (q *Queries) UpdateNovelChapterContent(ctx context.Context, arg UpdateNovelChapterContentParams) (NovelChapter, error) {
	row := q.db.QueryRow(ctx, updateNovelChapterContent, arg.ID, arg.ContentHtml, arg.ContentJson)
	var i NovelChapter
	err := row.Scan(
		&i.ID,
		&i.NovelProjectID,
		&i.Title,
		&i.OrderIndex,
		&i.ContentHtml,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
