// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: novel_projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNovelProject = `-- name: CreateNovelProject :one
INSERT INTO novel_projects (project_id, title, description, language, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, description, language, created_at, updated_at
`

type CreateNovelProjectParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Language    pgtype.Text `json:"language"`
	OrgID       pgtype.Text `json:"org_id"`
}

type CreateNovelProjectRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Language    pgtype.Text        `json:"language"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateNovelProject(ctx context.Context, arg CreateNovelProjectParams) (CreateNovelProjectRow, error) {
	row := q.db.QueryRow(ctx, createNovelProject,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.OrgID,
	)
	var i CreateNovelProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNovelProject = `-- name: DeleteNovelProject :exec
DELETE FROM novel_projects WHERE id = $1
`

func (q *Queries) DeleteNovelProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNovelProject, id)
	return err
}

const getNovelProject = `-- name: GetNovelProject :one
SELECT id, project_id, title, description, language, created_at, updated_at
FROM novel_projects
WHERE id = $1
`

type GetNovelProjectRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Language    pgtype.Text        `json:"language"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNovelProject(ctx context.Context, id pgtype.UUID) (GetNovelProjectRow, error) {
	row := q.db.QueryRow(ctx, getNovelProject, id)
	var i GetNovelProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNovelProjectByProjectId = `-- name: GetNovelProjectByProjectId :one
SELECT id, project_id, title, description, language, created_at, updated_at
FROM novel_projects
WHERE project_id = $1
`

type GetNovelProjectByProjectIdRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Language    pgtype.Text        `json:"language"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNovelProjectByProjectId(ctx context.Context, projectID pgtype.UUID) (GetNovelProjectByProjectIdRow, error) {
	row := q.db.QueryRow(ctx, getNovelProjectByProjectId, projectID)
	var i GetNovelProjectByProjectIdRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNovelProjectOrgId = `-- name: GetNovelProjectOrgId :one
SELECT org_id FROM novel_projects WHERE id = $1
`

func (q *Queries) GetNovelProjectOrgId(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getNovelProjectOrgId, id)
	var org_id pgtype.Text
	err := row.Scan(&org_id)
	return org_id, err
}

const listNovelProjectsByProjectId = `-- name: ListNovelProjectsByProjectId :many
SELECT id, project_id, title, description, language, created_at, updated_at
FROM novel_projects
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListNovelProjectsByProjectIdRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Language    pgtype.Text        `json:"language"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNovelProjectsByProjectId(ctx context.Context, projectID pgtype.UUID) ([]ListNovelProjectsByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, listNovelProjectsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNovelProjectsByProjectIdRow
	for rows.Next() {
		var i ListNovelProjectsByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNovelProject = `-- name: UpdateNovelProject :one
UPDATE novel_projects
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    language = COALESCE($4, language),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, description, language, created_at, updated_at
`

type UpdateNovelProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Language    pgtype.Text `json:"language"`
}

type UpdateNovelProjectRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Language    pgtype.Text        `json:"language"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateNovelProject(ctx context.Context, arg UpdateNovelProjectParams) (UpdateNovelProjectRow, error) {
	row := q.db.QueryRow(ctx, updateNovelProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Language,
	)
	var i UpdateNovelProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
