// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenarios.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (scenario_id, title, description, order_index, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, scenario_id, title, description, order_index, created_at, updated_at
`

type CreateEpisodeParams struct {
	ScenarioID  pgtype.UUID `json:"scenario_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	OrderIndex  int32       `json:"order_index"`
	OrgID       pgtype.Text `json:"org_id"`
}

type CreateEpisodeRow struct {
	ID          pgtype.UUID        `json:"id"`
	ScenarioID  pgtype.UUID        `json:"scenario_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (CreateEpisodeRow, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.ScenarioID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.OrgID,
	)
	var i CreateEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPart = `-- name: CreatePart :one
INSERT INTO parts (episode_id, title, description, order_index, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, episode_id, title, description, order_index, created_at, updated_at
`

type CreatePartParams struct {
	EpisodeID   pgtype.UUID `json:"episode_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	OrderIndex  int32       `json:"order_index"`
	OrgID       pgtype.Text `json:"org_id"`
}

type CreatePartRow struct {
	ID          pgtype.UUID        `json:"id"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (CreatePartRow, error) {
	row := q.db.QueryRow(ctx, createPart,
		arg.EpisodeID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
		arg.OrgID,
	)
	var i CreatePartRow
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios (project_id, title, description, org_id)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, description, created_at, updated_at
`

type CreateScenarioParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	OrgID       pgtype.Text `json:"org_id"`
}

type CreateScenarioRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (CreateScenarioRow, error) {
	row := q.db.QueryRow(ctx, createScenario,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.OrgID,
	)
	var i CreateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScenePlan = `-- name: CreateScenePlan :one
INSERT INTO scene_plans (part_id, description, order_index, org_id)
VALUES ($1, $2, $3, $4)
RETURNING id, part_id, description, order_index, created_at, updated_at
`

type CreateScenePlanParams struct {
	PartID      pgtype.UUID `json:"part_id"`
	Description string      `json:"description"`
	OrderIndex  int32       `json:"order_index"`
	OrgID       pgtype.Text `json:"org_id"`
}

type CreateScenePlanRow struct {
	ID          pgtype.UUID        `json:"id"`
	PartID      pgtype.UUID        `json:"part_id"`
	Description string             `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateScenePlan(ctx context.Context, arg CreateScenePlanParams) (CreateScenePlanRow, error) {
	row := q.db.QueryRow(ctx, createScenePlan,
		arg.PartID,
		arg.Description,
		arg.OrderIndex,
		arg.OrgID,
	)
	var i CreateScenePlanRow
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes WHERE id = $1
`

func (q *Queries) DeleteEpisode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEpisode, id)
	return err
}

const deletePart = `-- name: DeletePart :exec
DELETE FROM parts WHERE id = $1
`

func (q *Queries) DeletePart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePart, id)
	return err
}

const deleteScenario = `-- name: DeleteScenario :exec
DELETE FROM scenarios WHERE id = $1
`

func (q *Queries) DeleteScenario(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScenario, id)
	return err
}

const deleteScenePlan = `-- name: DeleteScenePlan :exec
DELETE FROM scene_plans WHERE id = $1
`

func (q *Queries) DeleteScenePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScenePlan, id)
	return err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, scenario_id, title, description, order_index, created_at, updated_at
FROM episodes
WHERE id = $1
`

type GetEpisodeRow struct {
	ID          pgtype.UUID        `json:"id"`
	ScenarioID  pgtype.UUID        `json:"scenario_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEpisode(ctx context.Context, id pgtype.UUID) (GetEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getEpisode, id)
	var i GetEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPart = `-- name: GetPart :one
SELECT id, episode_id, title, description, order_index, created_at, updated_at
FROM parts
WHERE id = $1
`

type GetPartRow struct {
	ID          pgtype.UUID        `json:"id"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPart(ctx context.Context, id pgtype.UUID) (GetPartRow, error) {
	row := q.db.QueryRow(ctx, getPart, id)
	var i GetPartRow
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, project_id, title, description, created_at, updated_at
FROM scenarios
WHERE id = $1
`

type GetScenarioRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetScenario(ctx context.Context, id pgtype.UUID) (GetScenarioRow, error) {
	row := q.db.QueryRow(ctx, getScenario, id)
	var i GetScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenePlan = `-- name: GetScenePlan :one
SELECT id, part_id, description, order_index, created_at, updated_at
FROM scene_plans
WHERE id = $1
`

type GetScenePlanRow struct {
	ID          pgtype.UUID        `json:"id"`
	PartID      pgtype.UUID        `json:"part_id"`
	Description string             `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetScenePlan(ctx context.Context, id pgtype.UUID) (GetScenePlanRow, error) {
	row := q.db.QueryRow(ctx, getScenePlan, id)
	var i GetScenePlanRow
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT id, scenario_id, title, description, order_index, created_at, updated_at
FROM episodes
WHERE scenario_id = $1
ORDER BY order_index ASC
`

type ListEpisodesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ScenarioID  pgtype.UUID        `json:"scenario_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEpisodes(ctx context.Context, scenarioID pgtype.UUID) ([]ListEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listEpisodes, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodesRow
	for rows.Next() {
		var i ListEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParts = `-- name: ListParts :many
SELECT id, episode_id, title, description, order_index, created_at, updated_at
FROM parts
WHERE episode_id = $1
ORDER BY order_index ASC
`

type ListPartsRow struct {
	ID          pgtype.UUID        `json:"id"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListParts(ctx context.Context, episodeID pgtype.UUID) ([]ListPartsRow, error) {
	rows, err := q.db.Query(ctx, listParts, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsRow
	for rows.Next() {
		var i ListPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarios = `-- name: ListScenarios :many
SELECT id, project_id, title, description, created_at, updated_at
FROM scenarios
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListScenariosRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListScenarios(ctx context.Context, projectID pgtype.UUID) ([]ListScenariosRow, error) {
	rows, err := q.db.Query(ctx, listScenarios, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosRow
	for rows.Next() {
		var i ListScenariosRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenePlans = `-- name: ListScenePlans :many
SELECT id, part_id, description, order_index, created_at, updated_at
FROM scene_plans
WHERE part_id = $1
ORDER BY order_index ASC
`

type ListScenePlansRow struct {
	ID          pgtype.UUID        `json:"id"`
	PartID      pgtype.UUID        `json:"part_id"`
	Description string             `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListScenePlans(ctx context.Context, partID pgtype.UUID) ([]ListScenePlansRow, error) {
	rows, err := q.db.Query(ctx, listScenePlans, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenePlansRow
	for rows.Next() {
		var i ListScenePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisode = `-- name: UpdateEpisode :one
UPDATE episodes
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    order_index = COALESCE($4, order_index),
    updated_at = NOW()
WHERE id = $1
RETURNING id, scenario_id, title, description, order_index, created_at, updated_at
`

type UpdateEpisodeParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	OrderIndex  int32       `json:"order_index"`
}

type UpdateEpisodeRow struct {
	ID          pgtype.UUID        `json:"id"`
	ScenarioID  pgtype.UUID        `json:"scenario_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (UpdateEpisodeRow, error) {
	row := q.db.QueryRow(ctx, updateEpisode,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
	)
	var i UpdateEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePart = `-- name: UpdatePart :one
UPDATE parts
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    order_index = COALESCE($4, order_index),
    updated_at = NOW()
WHERE id = $1
RETURNING id, episode_id, title, description, order_index, created_at, updated_at
`

type UpdatePartParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	OrderIndex  int32       `json:"order_index"`
}

type UpdatePartRow struct {
	ID          pgtype.UUID        `json:"id"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) (UpdatePartRow, error) {
	row := q.db.QueryRow(ctx, updatePart,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OrderIndex,
	)
	var i UpdatePartRow
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.Title,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScenario = `-- name: UpdateScenario :one
UPDATE scenarios
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, description, created_at, updated_at
`

type UpdateScenarioParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

type UpdateScenarioRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (UpdateScenarioRow, error) {
	row := q.db.QueryRow(ctx, updateScenario, arg.ID, arg.Title, arg.Description)
	var i UpdateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScenePlan = `-- name: UpdateScenePlan :one
UPDATE scene_plans
SET description = COALESCE($2, description),
    order_index = COALESCE($3, order_index),
    updated_at = NOW()
WHERE id = $1
RETURNING id, part_id, description, order_index, created_at, updated_at
`

type UpdateScenePlanParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	OrderIndex  int32       `json:"order_index"`
}

type UpdateScenePlanRow struct {
	ID          pgtype.UUID        `json:"id"`
	PartID      pgtype.UUID        `json:"part_id"`
	Description string             `json:"description"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateScenePlan(ctx context.Context, arg UpdateScenePlanParams) (UpdateScenePlanRow, error) {
	row := q.db.QueryRow(ctx, updateScenePlan, arg.ID, arg.Description, arg.OrderIndex)
	var i UpdateScenePlanRow
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.Description,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
