// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: speech_bubbles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpeechBubble = `-- name: CreateSpeechBubble :one
INSERT INTO speech_bubbles (panel_id, bubble_type, text, speaker, x, y, width, height)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, panel_id, bubble_type, text, speaker, x, y, width, height, created_at, updated_at
`

type CreateSpeechBubbleParams struct {
	PanelID    pgtype.UUID   `json:"panel_id"`
	BubbleType string        `json:"bubble_type"`
	Text       string        `json:"text"`
	Speaker    pgtype.Text   `json:"speaker"`
	X          pgtype.Float8 `json:"x"`
	Y          pgtype.Float8 `json:"y"`
	Width      pgtype.Float8 `json:"width"`
	Height     pgtype.Float8 `json:"height"`
}

func (q *Queries) CreateSpeechBubble(ctx context.Context, arg CreateSpeechBubbleParams) (SpeechBubble, error) {
	row := q.db.QueryRow(ctx, createSpeechBubble,
		arg.PanelID,
		arg.BubbleType,
		arg.Text,
		arg.Speaker,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
	)
	var i SpeechBubble
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.BubbleType,
		&i.Text,
		&i.Speaker,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpeechBubble = `-- name: DeleteSpeechBubble :exec
DELETE FROM speech_bubbles WHERE id = $1
`

func (q *Queries) DeleteSpeechBubble(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpeechBubble, id)
	return err
}

const getSpeechBubble = `-- name: GetSpeechBubble :one
SELECT id, panel_id, bubble_type, text, speaker, x, y, width, height, created_at, updated_at
FROM speech_bubbles
WHERE id = $1
`

func (q *Queries) GetSpeechBubble(ctx context.Context, id pgtype.UUID) (SpeechBubble, error) {
	row := q.db.QueryRow(ctx, getSpeechBubble, id)
	var i SpeechBubble
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.BubbleType,
		&i.Text,
		&i.Speaker,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpeechBubbles = `-- name: ListSpeechBubbles :many
SELECT id, panel_id, bubble_type, text, speaker, x, y, width, height, created_at, updated_at
FROM speech_bubbles
WHERE panel_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListSpeechBubbles(ctx context.Context, panelID pgtype.UUID) ([]SpeechBubble, error) {
	rows, err := q.db.Query(ctx, listSpeechBubbles, panelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpeechBubble
	for rows.Next() {
		var i SpeechBubble
		if err := rows.Scan(
			&i.ID,
			&i.PanelID,
			&i.BubbleType,
			&i.Text,
			&i.Speaker,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpeechBubble = `-- name: UpdateSpeechBubble :one
UPDATE speech_bubbles
SET bubble_type = COALESCE($2, bubble_type),
    text = COALESCE($3, text),
    speaker = COALESCE($4, speaker),
    x = COALESCE($5, x),
    y = COALESCE($6, y),
    width = COALESCE($7, width),
    height = COALESCE($8, height),
    updated_at = NOW()
WHERE id = $1
RETURNING id, panel_id, bubble_type, text, speaker, x, y, width, height, created_at, updated_at
`

type UpdateSpeechBubbleParams struct {
	ID         pgtype.UUID   `json:"id"`
	BubbleType string        `json:"bubble_type"`
	Text       string        `json:"text"`
	Speaker    pgtype.Text   `json:"speaker"`
	X          pgtype.Float8 `json:"x"`
	Y          pgtype.Float8 `json:"y"`
	Width      pgtype.Float8 `json:"width"`
	Height     pgtype.Float8 `json:"height"`
}

func (q *Queries) UpdateSpeechBubble(ctx context.Context, arg UpdateSpeechBubbleParams) (SpeechBubble, error) {
	row := q.db.QueryRow(ctx, updateSpeechBubble,
		arg.ID,
		arg.BubbleType,
		arg.Text,
		arg.Speaker,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
	)
	var i SpeechBubble
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.BubbleType,
		&i.Text,
		&i.Speaker,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
