// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: world_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorldSetting = `-- name: CreateWorldSetting :one
INSERT INTO world_settings (project_id, org_id, name, description, setting_type, time_period, geography, climate, culture, politics, economy, magic_system, rules, history, attributes_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, project_id, org_id, name, description, setting_type, time_period, geography, climate, culture, politics, economy, magic_system, rules, history, attributes_json, created_at, updated_at
`

type CreateWorldSettingParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	OrgID          pgtype.Text `json:"org_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	SettingType    pgtype.Text `json:"setting_type"`
	TimePeriod     pgtype.Text `json:"time_period"`
	Geography      pgtype.Text `json:"geography"`
	Climate        pgtype.Text `json:"climate"`
	Culture        pgtype.Text `json:"culture"`
	Politics       pgtype.Text `json:"politics"`
	Economy        pgtype.Text `json:"economy"`
	MagicSystem    pgtype.Text `json:"magic_system"`
	Rules          pgtype.Text `json:"rules"`
	History        pgtype.Text `json:"history"`
	AttributesJson []byte      `json:"attributes_json"`
}

func (q *Queries) CreateWorldSetting(ctx context.Context, arg CreateWorldSettingParams) (WorldSetting, error) {
	row := q.db.QueryRow(ctx, createWorldSetting,
		arg.ProjectID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.SettingType,
		arg.TimePeriod,
		arg.Geography,
		arg.Climate,
		arg.Culture,
		arg.Politics,
		arg.Economy,
		arg.MagicSystem,
		arg.Rules,
		arg.History,
		arg.AttributesJson,
	)
	var i WorldSetting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.SettingType,
		&i.TimePeriod,
		&i.Geography,
		&i.Climate,
		&i.Culture,
		&i.Politics,
		&i.Economy,
		&i.MagicSystem,
		&i.Rules,
		&i.History,
		&i.AttributesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorldSetting = `-- name: DeleteWorldSetting :exec
DELETE FROM world_settings WHERE id = $1
`

func (q *Queries) DeleteWorldSetting(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorldSetting, id)
	return err
}

const getWorldSetting = `-- name: GetWorldSetting :one
SELECT id, project_id, org_id, name, description, setting_type, time_period, geography, climate, culture, politics, economy, magic_system, rules, history, attributes_json, created_at, updated_at
FROM world_settings
WHERE id = $1
`

func (q *Queries) GetWorldSetting(ctx context.Context, id pgtype.UUID) (WorldSetting, error) {
	row := q.db.QueryRow(ctx, getWorldSetting, id)
	var i WorldSetting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.SettingType,
		&i.TimePeriod,
		&i.Geography,
		&i.Climate,
		&i.Culture,
		&i.Politics,
		&i.Economy,
		&i.MagicSystem,
		&i.Rules,
		&i.History,
		&i.AttributesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorldSettings = `-- name: ListWorldSettings :many
SELECT id, project_id, org_id, name, description, setting_type, time_period, geography, climate, culture, politics, economy, magic_system, rules, history, attributes_json, created_at, updated_at
FROM world_settings
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorldSettings(ctx context.Context, projectID pgtype.UUID) ([]WorldSetting, error) {
	rows, err := q.db.Query(ctx, listWorldSettings, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldSetting
	for rows.Next() {
		var i WorldSetting
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.SettingType,
			&i.TimePeriod,
			&i.Geography,
			&i.Climate,
			&i.Culture,
			&i.Politics,
			&i.Economy,
			&i.MagicSystem,
			&i.Rules,
			&i.History,
			&i.AttributesJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorldSetting = `-- name: UpdateWorldSetting :one
UPDATE world_settings
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    setting_type = COALESCE($4, setting_type),
    time_period = COALESCE($5, time_period),
    geography = COALESCE($6, geography),
    climate = COALESCE($7, climate),
    culture = COALESCE($8, culture),
    politics = COALESCE($9, politics),
    economy = COALESCE($10, economy),
    magic_system = COALESCE($11, magic_system),
    rules = COALESCE($12, rules),
    history = COALESCE($13, history),
    attributes_json = COALESCE($14, attributes_json),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, org_id, name, description, setting_type, time_period, geography, climate, culture, politics, economy, magic_system, rules, history, attributes_json, created_at, updated_at
`

type UpdateWorldSettingParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	SettingType    pgtype.Text `json:"setting_type"`
	TimePeriod     pgtype.Text `json:"time_period"`
	Geography      pgtype.Text `json:"geography"`
	Climate        pgtype.Text `json:"climate"`
	Culture        pgtype.Text `json:"culture"`
	Politics       pgtype.Text `json:"politics"`
	Economy        pgtype.Text `json:"economy"`
	MagicSystem    pgtype.Text `json:"magic_system"`
	Rules          pgtype.Text `json:"rules"`
	History        pgtype.Text `json:"history"`
	AttributesJson []byte      `json:"attributes_json"`
}

func (q *Queries) UpdateWorldSetting(ctx context.Context, arg UpdateWorldSettingParams) (WorldSetting, error) {
	row := q.db.QueryRow(ctx, updateWorldSetting,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SettingType,
		arg.TimePeriod,
		arg.Geography,
		arg.Climate,
		arg.Culture,
		arg.Politics,
		arg.Economy,
		arg.MagicSystem,
		arg.Rules,
		arg.History,
		arg.AttributesJson,
	)
	var i WorldSetting
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.SettingType,
		&i.TimePeriod,
		&i.Geography,
		&i.Climate,
		&i.Culture,
		&i.Politics,
		&i.Economy,
		&i.MagicSystem,
		&i.Rules,
		&i.History,
		&i.AttributesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
