query ListCharacters($projectId: ID!) {
	characters(projectId: $projectId) {
		id
		projectId
		name
		description
		personality
		background
		defaultHumeVoiceId
		profileImageId
		assets {
			id
			characterId
			assetType
			assetFormat
			createdAt
			updatedAt
		}
		createdAt
		updatedAt
	}
}

