// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/editor.proto

package editorpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/gftd-ai/ghost-hacker/apps/zen-editor/backend/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EditorServiceName is the fully-qualified name of the EditorService service.
	EditorServiceName = "gftd.ghosthacker.zeneditor.v1.EditorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EditorServiceAnalyzeTextProcedure is the fully-qualified name of the EditorService's AnalyzeText
	// RPC.
	EditorServiceAnalyzeTextProcedure = "/gftd.ghosthacker.zeneditor.v1.EditorService/AnalyzeText"
	// EditorServiceGetTopologyProcedure is the fully-qualified name of the EditorService's GetTopology
	// RPC.
	EditorServiceGetTopologyProcedure = "/gftd.ghosthacker.zeneditor.v1.EditorService/GetTopology"
	// EditorServiceGetProjectMetadataProcedure is the fully-qualified name of the EditorService's
	// GetProjectMetadata RPC.
	EditorServiceGetProjectMetadataProcedure = "/gftd.ghosthacker.zeneditor.v1.EditorService/GetProjectMetadata"
	// EditorServiceOpenFileProcedure is the fully-qualified name of the EditorService's OpenFile RPC.
	EditorServiceOpenFileProcedure = "/gftd.ghosthacker.zeneditor.v1.EditorService/OpenFile"
	// EditorServiceSaveFileProcedure is the fully-qualified name of the EditorService's SaveFile RPC.
	EditorServiceSaveFileProcedure = "/gftd.ghosthacker.zeneditor.v1.EditorService/SaveFile"
)

// EditorServiceClient is a client for the gftd.ghosthacker.zeneditor.v1.EditorService service.
type EditorServiceClient interface {
	AnalyzeText(context.Context, *connect.Request[proto.AnalyzeTextRequest]) (*connect.Response[proto.AnalyzeTextResponse], error)
	GetTopology(context.Context, *connect.Request[proto.GetTopologyRequest]) (*connect.Response[proto.GetTopologyResponse], error)
	GetProjectMetadata(context.Context, *connect.Request[proto.GetProjectMetadataRequest]) (*connect.Response[proto.GetProjectMetadataResponse], error)
	OpenFile(context.Context, *connect.Request[proto.OpenFileRequest]) (*connect.Response[proto.OpenFileResponse], error)
	SaveFile(context.Context, *connect.Request[proto.SaveFileRequest]) (*connect.Response[proto.SaveFileResponse], error)
}

// NewEditorServiceClient constructs a client for the gftd.ghosthacker.zeneditor.v1.EditorService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEditorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EditorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	editorServiceMethods := proto.File_proto_editor_proto.Services().ByName("EditorService").Methods()
	return &editorServiceClient{
		analyzeText: connect.NewClient[proto.AnalyzeTextRequest, proto.AnalyzeTextResponse](
			httpClient,
			baseURL+EditorServiceAnalyzeTextProcedure,
			connect.WithSchema(editorServiceMethods.ByName("AnalyzeText")),
			connect.WithClientOptions(opts...),
		),
		getTopology: connect.NewClient[proto.GetTopologyRequest, proto.GetTopologyResponse](
			httpClient,
			baseURL+EditorServiceGetTopologyProcedure,
			connect.WithSchema(editorServiceMethods.ByName("GetTopology")),
			connect.WithClientOptions(opts...),
		),
		getProjectMetadata: connect.NewClient[proto.GetProjectMetadataRequest, proto.GetProjectMetadataResponse](
			httpClient,
			baseURL+EditorServiceGetProjectMetadataProcedure,
			connect.WithSchema(editorServiceMethods.ByName("GetProjectMetadata")),
			connect.WithClientOptions(opts...),
		),
		openFile: connect.NewClient[proto.OpenFileRequest, proto.OpenFileResponse](
			httpClient,
			baseURL+EditorServiceOpenFileProcedure,
			connect.WithSchema(editorServiceMethods.ByName("OpenFile")),
			connect.WithClientOptions(opts...),
		),
		saveFile: connect.NewClient[proto.SaveFileRequest, proto.SaveFileResponse](
			httpClient,
			baseURL+EditorServiceSaveFileProcedure,
			connect.WithSchema(editorServiceMethods.ByName("SaveFile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// editorServiceClient implements EditorServiceClient.
type editorServiceClient struct {
	analyzeText        *connect.Client[proto.AnalyzeTextRequest, proto.AnalyzeTextResponse]
	getTopology        *connect.Client[proto.GetTopologyRequest, proto.GetTopologyResponse]
	getProjectMetadata *connect.Client[proto.GetProjectMetadataRequest, proto.GetProjectMetadataResponse]
	openFile           *connect.Client[proto.OpenFileRequest, proto.OpenFileResponse]
	saveFile           *connect.Client[proto.SaveFileRequest, proto.SaveFileResponse]
}

// AnalyzeText calls gftd.ghosthacker.zeneditor.v1.EditorService.AnalyzeText.
func (c *editorServiceClient) AnalyzeText(ctx context.Context, req *connect.Request[proto.AnalyzeTextRequest]) (*connect.Response[proto.AnalyzeTextResponse], error) {
	return c.analyzeText.CallUnary(ctx, req)
}

// GetTopology calls gftd.ghosthacker.zeneditor.v1.EditorService.GetTopology.
func (c *editorServiceClient) GetTopology(ctx context.Context, req *connect.Request[proto.GetTopologyRequest]) (*connect.Response[proto.GetTopologyResponse], error) {
	return c.getTopology.CallUnary(ctx, req)
}

// GetProjectMetadata calls gftd.ghosthacker.zeneditor.v1.EditorService.GetProjectMetadata.
func (c *editorServiceClient) GetProjectMetadata(ctx context.Context, req *connect.Request[proto.GetProjectMetadataRequest]) (*connect.Response[proto.GetProjectMetadataResponse], error) {
	return c.getProjectMetadata.CallUnary(ctx, req)
}

// OpenFile calls gftd.ghosthacker.zeneditor.v1.EditorService.OpenFile.
func (c *editorServiceClient) OpenFile(ctx context.Context, req *connect.Request[proto.OpenFileRequest]) (*connect.Response[proto.OpenFileResponse], error) {
	return c.openFile.CallUnary(ctx, req)
}

// SaveFile calls gftd.ghosthacker.zeneditor.v1.EditorService.SaveFile.
func (c *editorServiceClient) SaveFile(ctx context.Context, req *connect.Request[proto.SaveFileRequest]) (*connect.Response[proto.SaveFileResponse], error) {
	return c.saveFile.CallUnary(ctx, req)
}

// EditorServiceHandler is an implementation of the gftd.ghosthacker.zeneditor.v1.EditorService
// service.
type EditorServiceHandler interface {
	AnalyzeText(context.Context, *connect.Request[proto.AnalyzeTextRequest]) (*connect.Response[proto.AnalyzeTextResponse], error)
	GetTopology(context.Context, *connect.Request[proto.GetTopologyRequest]) (*connect.Response[proto.GetTopologyResponse], error)
	GetProjectMetadata(context.Context, *connect.Request[proto.GetProjectMetadataRequest]) (*connect.Response[proto.GetProjectMetadataResponse], error)
	OpenFile(context.Context, *connect.Request[proto.OpenFileRequest]) (*connect.Response[proto.OpenFileResponse], error)
	SaveFile(context.Context, *connect.Request[proto.SaveFileRequest]) (*connect.Response[proto.SaveFileResponse], error)
}

// NewEditorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEditorServiceHandler(svc EditorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	editorServiceMethods := proto.File_proto_editor_proto.Services().ByName("EditorService").Methods()
	editorServiceAnalyzeTextHandler := connect.NewUnaryHandler(
		EditorServiceAnalyzeTextProcedure,
		svc.AnalyzeText,
		connect.WithSchema(editorServiceMethods.ByName("AnalyzeText")),
		connect.WithHandlerOptions(opts...),
	)
	editorServiceGetTopologyHandler := connect.NewUnaryHandler(
		EditorServiceGetTopologyProcedure,
		svc.GetTopology,
		connect.WithSchema(editorServiceMethods.ByName("GetTopology")),
		connect.WithHandlerOptions(opts...),
	)
	editorServiceGetProjectMetadataHandler := connect.NewUnaryHandler(
		EditorServiceGetProjectMetadataProcedure,
		svc.GetProjectMetadata,
		connect.WithSchema(editorServiceMethods.ByName("GetProjectMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	editorServiceOpenFileHandler := connect.NewUnaryHandler(
		EditorServiceOpenFileProcedure,
		svc.OpenFile,
		connect.WithSchema(editorServiceMethods.ByName("OpenFile")),
		connect.WithHandlerOptions(opts...),
	)
	editorServiceSaveFileHandler := connect.NewUnaryHandler(
		EditorServiceSaveFileProcedure,
		svc.SaveFile,
		connect.WithSchema(editorServiceMethods.ByName("SaveFile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gftd.ghosthacker.zeneditor.v1.EditorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EditorServiceAnalyzeTextProcedure:
			editorServiceAnalyzeTextHandler.ServeHTTP(w, r)
		case EditorServiceGetTopologyProcedure:
			editorServiceGetTopologyHandler.ServeHTTP(w, r)
		case EditorServiceGetProjectMetadataProcedure:
			editorServiceGetProjectMetadataHandler.ServeHTTP(w, r)
		case EditorServiceOpenFileProcedure:
			editorServiceOpenFileHandler.ServeHTTP(w, r)
		case EditorServiceSaveFileProcedure:
			editorServiceSaveFileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEditorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEditorServiceHandler struct{}

func (UnimplementedEditorServiceHandler) AnalyzeText(context.Context, *connect.Request[proto.AnalyzeTextRequest]) (*connect.Response[proto.AnalyzeTextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gftd.ghosthacker.zeneditor.v1.EditorService.AnalyzeText is not implemented"))
}

func (UnimplementedEditorServiceHandler) GetTopology(context.Context, *connect.Request[proto.GetTopologyRequest]) (*connect.Response[proto.GetTopologyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gftd.ghosthacker.zeneditor.v1.EditorService.GetTopology is not implemented"))
}

func (UnimplementedEditorServiceHandler) GetProjectMetadata(context.Context, *connect.Request[proto.GetProjectMetadataRequest]) (*connect.Response[proto.GetProjectMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gftd.ghosthacker.zeneditor.v1.EditorService.GetProjectMetadata is not implemented"))
}

func (UnimplementedEditorServiceHandler) OpenFile(context.Context, *connect.Request[proto.OpenFileRequest]) (*connect.Response[proto.OpenFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gftd.ghosthacker.zeneditor.v1.EditorService.OpenFile is not implemented"))
}

func (UnimplementedEditorServiceHandler) SaveFile(context.Context, *connect.Request[proto.SaveFileRequest]) (*connect.Response[proto.SaveFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gftd.ghosthacker.zeneditor.v1.EditorService.SaveFile is not implemented"))
}
