package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"github.com/gftd/epub-editor-graphql-go/internal/ports"
)

// Resolver is the root resolver
type Resolver struct {
	neo4jPool *ports.Neo4jPool
}

// NewResolver creates a new resolver
func NewResolver(neo4jPool *ports.Neo4jPool) *Resolver {
	return &Resolver{
		neo4jPool: neo4jPool,
	}
}
