package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/gftd/epub-editor-graphql-go/graph"
	"github.com/gftd/epub-editor-graphql-go/graph/model"
)

// CreateEpub is the resolver for the createEpub field.
func (r *mutationResolver) CreateEpub(ctx context.Context, input model.CreateEpubInput) (*model.Epub, error) {
	panic(fmt.Errorf("not implemented: CreateEpub - createEpub"))
}

// UpdateEpub is the resolver for the updateEpub field.
func (r *mutationResolver) UpdateEpub(ctx context.Context, input model.UpdateEpubInput) (*model.Epub, error) {
	panic(fmt.Errorf("not implemented: UpdateEpub - updateEpub"))
}

// DeleteEpub is the resolver for the deleteEpub field.
func (r *mutationResolver) DeleteEpub(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteEpub - deleteEpub"))
}

// CreateChapter is the resolver for the createChapter field.
func (r *mutationResolver) CreateChapter(ctx context.Context, input model.CreateChapterInput) (*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: CreateChapter - createChapter"))
}

// UpdateChapter is the resolver for the updateChapter field.
func (r *mutationResolver) UpdateChapter(ctx context.Context, input model.UpdateChapterInput) (*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: UpdateChapter - updateChapter"))
}

// DeleteChapter is the resolver for the deleteChapter field.
func (r *mutationResolver) DeleteChapter(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteChapter - deleteChapter"))
}

// CreateMedia is the resolver for the createMedia field.
func (r *mutationResolver) CreateMedia(ctx context.Context, input model.CreateMediaInput) (*model.Media, error) {
	panic(fmt.Errorf("not implemented: CreateMedia - createMedia"))
}

// UpdateMetadata is the resolver for the updateMetadata field.
func (r *mutationResolver) UpdateMetadata(ctx context.Context, input model.UpdateMetadataInput) (*model.MetadataItem, error) {
	panic(fmt.Errorf("not implemented: UpdateMetadata - updateMetadata"))
}

// GenerateText is the resolver for the generateText field.
func (r *mutationResolver) GenerateText(ctx context.Context, input model.GenerateTextInput) (*model.GeneratedText, error) {
	panic(fmt.Errorf("not implemented: GenerateText - generateText"))
}

// Summarize is the resolver for the summarize field.
func (r *mutationResolver) Summarize(ctx context.Context, input model.SummarizeInput) (*model.GeneratedText, error) {
	panic(fmt.Errorf("not implemented: Summarize - summarize"))
}

// Proofread is the resolver for the proofread field.
func (r *mutationResolver) Proofread(ctx context.Context, input model.ProofreadInput) (*model.GeneratedText, error) {
	panic(fmt.Errorf("not implemented: Proofread - proofread"))
}

// Translate is the resolver for the translate field.
func (r *mutationResolver) Translate(ctx context.Context, input model.TranslateInput) (*model.GeneratedText, error) {
	panic(fmt.Errorf("not implemented: Translate - translate"))
}

// Epub is the resolver for the epub field.
func (r *queryResolver) Epub(ctx context.Context, id string) (*model.Epub, error) {
	panic(fmt.Errorf("not implemented: Epub - epub"))
}

// EpubList is the resolver for the epubList field.
func (r *queryResolver) EpubList(ctx context.Context) ([]*model.Epub, error) {
	panic(fmt.Errorf("not implemented: EpubList - epubList"))
}

// Chapter is the resolver for the chapter field.
func (r *queryResolver) Chapter(ctx context.Context, id string) (*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: Chapter - chapter"))
}

// Chapters is the resolver for the chapters field.
func (r *queryResolver) Chapters(ctx context.Context, epubID string) ([]*model.Chapter, error) {
	panic(fmt.Errorf("not implemented: Chapters - chapters"))
}

// Media is the resolver for the media field.
func (r *queryResolver) Media(ctx context.Context, id string) (*model.Media, error) {
	panic(fmt.Errorf("not implemented: Media - media"))
}

// Metadata is the resolver for the metadata field.
func (r *queryResolver) Metadata(ctx context.Context, epubID string) ([]*model.MetadataItem, error) {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// Empty is the resolver for the _empty field.
func (r *subscriptionResolver) Empty(ctx context.Context) (<-chan *string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
