{{- if .Values.postgresql.enabled }}
# Create temporal database for Temporal server
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "producer-storyboard.fullname" . }}-postgres-init
  labels:
    {{- include "producer-storyboard.labels" . | nindent 4 }}
data:
  init-temporal-db.sh: |
    #!/bin/bash
    set -e
    PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -d $POSTGRES_DB <<-EOSQL
      CREATE DATABASE temporal;
      GRANT ALL PRIVILEGES ON DATABASE temporal TO $POSTGRES_USER;
    EOSQL
---
{{- end }}
